<?php
/**
 * GetCharactersCharacterIdAttributesOk
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;

/**
 * GetCharactersCharacterIdAttributesOk Class Doc Comment
 *
 * @category    Class */
 // @description 200 ok object
/** 
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GetCharactersCharacterIdAttributesOk implements ArrayAccess
{
    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'get_characters_character_id_attributes_ok';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = array(
        'accrued_remap_cooldown_date' => '\DateTime',
        'bonus_remaps' => 'int',
        'charisma' => 'int',
        'intelligence' => 'int',
        'last_remap_date' => '\DateTime',
        'memory' => 'int',
        'perception' => 'int',
        'willpower' => 'int'
    );

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = array(
        'accrued_remap_cooldown_date' => 'accrued_remap_cooldown_date',
        'bonus_remaps' => 'bonus_remaps',
        'charisma' => 'charisma',
        'intelligence' => 'intelligence',
        'last_remap_date' => 'last_remap_date',
        'memory' => 'memory',
        'perception' => 'perception',
        'willpower' => 'willpower'
    );

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = array(
        'accrued_remap_cooldown_date' => 'setAccruedRemapCooldownDate',
        'bonus_remaps' => 'setBonusRemaps',
        'charisma' => 'setCharisma',
        'intelligence' => 'setIntelligence',
        'last_remap_date' => 'setLastRemapDate',
        'memory' => 'setMemory',
        'perception' => 'setPerception',
        'willpower' => 'setWillpower'
    );

    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = array(
        'accrued_remap_cooldown_date' => 'getAccruedRemapCooldownDate',
        'bonus_remaps' => 'getBonusRemaps',
        'charisma' => 'getCharisma',
        'intelligence' => 'getIntelligence',
        'last_remap_date' => 'getLastRemapDate',
        'memory' => 'getMemory',
        'perception' => 'getPerception',
        'willpower' => 'getWillpower'
    );

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = array();

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['accrued_remap_cooldown_date'] = isset($data['accrued_remap_cooldown_date']) ? $data['accrued_remap_cooldown_date'] : null;
        $this->container['bonus_remaps'] = isset($data['bonus_remaps']) ? $data['bonus_remaps'] : null;
        $this->container['charisma'] = isset($data['charisma']) ? $data['charisma'] : null;
        $this->container['intelligence'] = isset($data['intelligence']) ? $data['intelligence'] : null;
        $this->container['last_remap_date'] = isset($data['last_remap_date']) ? $data['last_remap_date'] : null;
        $this->container['memory'] = isset($data['memory']) ? $data['memory'] : null;
        $this->container['perception'] = isset($data['perception']) ? $data['perception'] : null;
        $this->container['willpower'] = isset($data['willpower']) ? $data['willpower'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = array();
        if ($this->container['charisma'] === null) {
            $invalid_properties[] = "'charisma' can't be null";
        }
        if ($this->container['intelligence'] === null) {
            $invalid_properties[] = "'intelligence' can't be null";
        }
        if ($this->container['memory'] === null) {
            $invalid_properties[] = "'memory' can't be null";
        }
        if ($this->container['perception'] === null) {
            $invalid_properties[] = "'perception' can't be null";
        }
        if ($this->container['willpower'] === null) {
            $invalid_properties[] = "'willpower' can't be null";
        }
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properteis are valid
     */
    public function valid()
    {
        if ($this->container['charisma'] === null) {
            return false;
        }
        if ($this->container['intelligence'] === null) {
            return false;
        }
        if ($this->container['memory'] === null) {
            return false;
        }
        if ($this->container['perception'] === null) {
            return false;
        }
        if ($this->container['willpower'] === null) {
            return false;
        }
        return true;
    }


    /**
     * Gets accrued_remap_cooldown_date
     * @return \DateTime
     */
    public function getAccruedRemapCooldownDate()
    {
        return $this->container['accrued_remap_cooldown_date'];
    }

    /**
     * Sets accrued_remap_cooldown_date
     * @param \DateTime $accrued_remap_cooldown_date Neural remapping cooldown after a character uses remap accrued over time
     * @return $this
     */
    public function setAccruedRemapCooldownDate($accrued_remap_cooldown_date)
    {
        $this->container['accrued_remap_cooldown_date'] = $accrued_remap_cooldown_date;

        return $this;
    }

    /**
     * Gets bonus_remaps
     * @return int
     */
    public function getBonusRemaps()
    {
        return $this->container['bonus_remaps'];
    }

    /**
     * Sets bonus_remaps
     * @param int $bonus_remaps Number of available bonus character neural remaps
     * @return $this
     */
    public function setBonusRemaps($bonus_remaps)
    {
        $this->container['bonus_remaps'] = $bonus_remaps;

        return $this;
    }

    /**
     * Gets charisma
     * @return int
     */
    public function getCharisma()
    {
        return $this->container['charisma'];
    }

    /**
     * Sets charisma
     * @param int $charisma charisma integer
     * @return $this
     */
    public function setCharisma($charisma)
    {
        $this->container['charisma'] = $charisma;

        return $this;
    }

    /**
     * Gets intelligence
     * @return int
     */
    public function getIntelligence()
    {
        return $this->container['intelligence'];
    }

    /**
     * Sets intelligence
     * @param int $intelligence intelligence integer
     * @return $this
     */
    public function setIntelligence($intelligence)
    {
        $this->container['intelligence'] = $intelligence;

        return $this;
    }

    /**
     * Gets last_remap_date
     * @return \DateTime
     */
    public function getLastRemapDate()
    {
        return $this->container['last_remap_date'];
    }

    /**
     * Sets last_remap_date
     * @param \DateTime $last_remap_date Datetime of last neural remap, including usage of bonus remaps
     * @return $this
     */
    public function setLastRemapDate($last_remap_date)
    {
        $this->container['last_remap_date'] = $last_remap_date;

        return $this;
    }

    /**
     * Gets memory
     * @return int
     */
    public function getMemory()
    {
        return $this->container['memory'];
    }

    /**
     * Sets memory
     * @param int $memory memory integer
     * @return $this
     */
    public function setMemory($memory)
    {
        $this->container['memory'] = $memory;

        return $this;
    }

    /**
     * Gets perception
     * @return int
     */
    public function getPerception()
    {
        return $this->container['perception'];
    }

    /**
     * Sets perception
     * @param int $perception perception integer
     * @return $this
     */
    public function setPerception($perception)
    {
        $this->container['perception'] = $perception;

        return $this;
    }

    /**
     * Gets willpower
     * @return int
     */
    public function getWillpower()
    {
        return $this->container['willpower'];
    }

    /**
     * Sets willpower
     * @param int $willpower willpower integer
     * @return $this
     */
    public function setWillpower($willpower)
    {
        $this->container['willpower'] = $willpower;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


