<?php
/**
 * GetDogmaEffectsEffectIdOk
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.7.5
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;

/**
 * GetDogmaEffectsEffectIdOk Class Doc Comment
 *
 * @category    Class */
 // @description 200 ok object
/** 
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GetDogmaEffectsEffectIdOk implements ArrayAccess
{
    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'get_dogma_effects_effect_id_ok';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = array(
        'effect_id' => 'int',
        'name' => 'string',
        'display_name' => 'string',
        'description' => 'string',
        'icon_id' => 'int',
        'effect_category' => 'int',
        'pre_expression' => 'int',
        'post_expression' => 'int',
        'is_offensive' => 'bool',
        'is_assistance' => 'bool',
        'disallow_auto_repeat' => 'bool',
        'published' => 'bool',
        'is_warp_safe' => 'bool',
        'range_chance' => 'bool',
        'electronic_chance' => 'bool',
        'duration_attribute_id' => 'int',
        'tracking_speed_attribute_id' => 'int',
        'discharge_attribute_id' => 'int',
        'range_attribute_id' => 'int',
        'falloff_attribute_id' => 'int',
        'modifiers' => '\Swagger\Client\Model\GetDogmaEffectsEffectIdOkModifiers[]'
    );

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = array(
        'effect_id' => 'effect_id',
        'name' => 'name',
        'display_name' => 'display_name',
        'description' => 'description',
        'icon_id' => 'icon_id',
        'effect_category' => 'effect_category',
        'pre_expression' => 'pre_expression',
        'post_expression' => 'post_expression',
        'is_offensive' => 'is_offensive',
        'is_assistance' => 'is_assistance',
        'disallow_auto_repeat' => 'disallow_auto_repeat',
        'published' => 'published',
        'is_warp_safe' => 'is_warp_safe',
        'range_chance' => 'range_chance',
        'electronic_chance' => 'electronic_chance',
        'duration_attribute_id' => 'duration_attribute_id',
        'tracking_speed_attribute_id' => 'tracking_speed_attribute_id',
        'discharge_attribute_id' => 'discharge_attribute_id',
        'range_attribute_id' => 'range_attribute_id',
        'falloff_attribute_id' => 'falloff_attribute_id',
        'modifiers' => 'modifiers'
    );

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = array(
        'effect_id' => 'setEffectId',
        'name' => 'setName',
        'display_name' => 'setDisplayName',
        'description' => 'setDescription',
        'icon_id' => 'setIconId',
        'effect_category' => 'setEffectCategory',
        'pre_expression' => 'setPreExpression',
        'post_expression' => 'setPostExpression',
        'is_offensive' => 'setIsOffensive',
        'is_assistance' => 'setIsAssistance',
        'disallow_auto_repeat' => 'setDisallowAutoRepeat',
        'published' => 'setPublished',
        'is_warp_safe' => 'setIsWarpSafe',
        'range_chance' => 'setRangeChance',
        'electronic_chance' => 'setElectronicChance',
        'duration_attribute_id' => 'setDurationAttributeId',
        'tracking_speed_attribute_id' => 'setTrackingSpeedAttributeId',
        'discharge_attribute_id' => 'setDischargeAttributeId',
        'range_attribute_id' => 'setRangeAttributeId',
        'falloff_attribute_id' => 'setFalloffAttributeId',
        'modifiers' => 'setModifiers'
    );

    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = array(
        'effect_id' => 'getEffectId',
        'name' => 'getName',
        'display_name' => 'getDisplayName',
        'description' => 'getDescription',
        'icon_id' => 'getIconId',
        'effect_category' => 'getEffectCategory',
        'pre_expression' => 'getPreExpression',
        'post_expression' => 'getPostExpression',
        'is_offensive' => 'getIsOffensive',
        'is_assistance' => 'getIsAssistance',
        'disallow_auto_repeat' => 'getDisallowAutoRepeat',
        'published' => 'getPublished',
        'is_warp_safe' => 'getIsWarpSafe',
        'range_chance' => 'getRangeChance',
        'electronic_chance' => 'getElectronicChance',
        'duration_attribute_id' => 'getDurationAttributeId',
        'tracking_speed_attribute_id' => 'getTrackingSpeedAttributeId',
        'discharge_attribute_id' => 'getDischargeAttributeId',
        'range_attribute_id' => 'getRangeAttributeId',
        'falloff_attribute_id' => 'getFalloffAttributeId',
        'modifiers' => 'getModifiers'
    );

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = array();

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['effect_id'] = isset($data['effect_id']) ? $data['effect_id'] : null;
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['display_name'] = isset($data['display_name']) ? $data['display_name'] : null;
        $this->container['description'] = isset($data['description']) ? $data['description'] : null;
        $this->container['icon_id'] = isset($data['icon_id']) ? $data['icon_id'] : null;
        $this->container['effect_category'] = isset($data['effect_category']) ? $data['effect_category'] : null;
        $this->container['pre_expression'] = isset($data['pre_expression']) ? $data['pre_expression'] : null;
        $this->container['post_expression'] = isset($data['post_expression']) ? $data['post_expression'] : null;
        $this->container['is_offensive'] = isset($data['is_offensive']) ? $data['is_offensive'] : null;
        $this->container['is_assistance'] = isset($data['is_assistance']) ? $data['is_assistance'] : null;
        $this->container['disallow_auto_repeat'] = isset($data['disallow_auto_repeat']) ? $data['disallow_auto_repeat'] : null;
        $this->container['published'] = isset($data['published']) ? $data['published'] : null;
        $this->container['is_warp_safe'] = isset($data['is_warp_safe']) ? $data['is_warp_safe'] : null;
        $this->container['range_chance'] = isset($data['range_chance']) ? $data['range_chance'] : null;
        $this->container['electronic_chance'] = isset($data['electronic_chance']) ? $data['electronic_chance'] : null;
        $this->container['duration_attribute_id'] = isset($data['duration_attribute_id']) ? $data['duration_attribute_id'] : null;
        $this->container['tracking_speed_attribute_id'] = isset($data['tracking_speed_attribute_id']) ? $data['tracking_speed_attribute_id'] : null;
        $this->container['discharge_attribute_id'] = isset($data['discharge_attribute_id']) ? $data['discharge_attribute_id'] : null;
        $this->container['range_attribute_id'] = isset($data['range_attribute_id']) ? $data['range_attribute_id'] : null;
        $this->container['falloff_attribute_id'] = isset($data['falloff_attribute_id']) ? $data['falloff_attribute_id'] : null;
        $this->container['modifiers'] = isset($data['modifiers']) ? $data['modifiers'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = array();
        if ($this->container['effect_id'] === null) {
            $invalid_properties[] = "'effect_id' can't be null";
        }
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properteis are valid
     */
    public function valid()
    {
        if ($this->container['effect_id'] === null) {
            return false;
        }
        return true;
    }


    /**
     * Gets effect_id
     * @return int
     */
    public function getEffectId()
    {
        return $this->container['effect_id'];
    }

    /**
     * Sets effect_id
     * @param int $effect_id effect_id integer
     * @return $this
     */
    public function setEffectId($effect_id)
    {
        $this->container['effect_id'] = $effect_id;

        return $this;
    }

    /**
     * Gets name
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     * @param string $name name string
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets display_name
     * @return string
     */
    public function getDisplayName()
    {
        return $this->container['display_name'];
    }

    /**
     * Sets display_name
     * @param string $display_name display_name string
     * @return $this
     */
    public function setDisplayName($display_name)
    {
        $this->container['display_name'] = $display_name;

        return $this;
    }

    /**
     * Gets description
     * @return string
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     * @param string $description description string
     * @return $this
     */
    public function setDescription($description)
    {
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets icon_id
     * @return int
     */
    public function getIconId()
    {
        return $this->container['icon_id'];
    }

    /**
     * Sets icon_id
     * @param int $icon_id icon_id integer
     * @return $this
     */
    public function setIconId($icon_id)
    {
        $this->container['icon_id'] = $icon_id;

        return $this;
    }

    /**
     * Gets effect_category
     * @return int
     */
    public function getEffectCategory()
    {
        return $this->container['effect_category'];
    }

    /**
     * Sets effect_category
     * @param int $effect_category effect_category integer
     * @return $this
     */
    public function setEffectCategory($effect_category)
    {
        $this->container['effect_category'] = $effect_category;

        return $this;
    }

    /**
     * Gets pre_expression
     * @return int
     */
    public function getPreExpression()
    {
        return $this->container['pre_expression'];
    }

    /**
     * Sets pre_expression
     * @param int $pre_expression pre_expression integer
     * @return $this
     */
    public function setPreExpression($pre_expression)
    {
        $this->container['pre_expression'] = $pre_expression;

        return $this;
    }

    /**
     * Gets post_expression
     * @return int
     */
    public function getPostExpression()
    {
        return $this->container['post_expression'];
    }

    /**
     * Sets post_expression
     * @param int $post_expression post_expression integer
     * @return $this
     */
    public function setPostExpression($post_expression)
    {
        $this->container['post_expression'] = $post_expression;

        return $this;
    }

    /**
     * Gets is_offensive
     * @return bool
     */
    public function getIsOffensive()
    {
        return $this->container['is_offensive'];
    }

    /**
     * Sets is_offensive
     * @param bool $is_offensive is_offensive boolean
     * @return $this
     */
    public function setIsOffensive($is_offensive)
    {
        $this->container['is_offensive'] = $is_offensive;

        return $this;
    }

    /**
     * Gets is_assistance
     * @return bool
     */
    public function getIsAssistance()
    {
        return $this->container['is_assistance'];
    }

    /**
     * Sets is_assistance
     * @param bool $is_assistance is_assistance boolean
     * @return $this
     */
    public function setIsAssistance($is_assistance)
    {
        $this->container['is_assistance'] = $is_assistance;

        return $this;
    }

    /**
     * Gets disallow_auto_repeat
     * @return bool
     */
    public function getDisallowAutoRepeat()
    {
        return $this->container['disallow_auto_repeat'];
    }

    /**
     * Sets disallow_auto_repeat
     * @param bool $disallow_auto_repeat disallow_auto_repeat boolean
     * @return $this
     */
    public function setDisallowAutoRepeat($disallow_auto_repeat)
    {
        $this->container['disallow_auto_repeat'] = $disallow_auto_repeat;

        return $this;
    }

    /**
     * Gets published
     * @return bool
     */
    public function getPublished()
    {
        return $this->container['published'];
    }

    /**
     * Sets published
     * @param bool $published published boolean
     * @return $this
     */
    public function setPublished($published)
    {
        $this->container['published'] = $published;

        return $this;
    }

    /**
     * Gets is_warp_safe
     * @return bool
     */
    public function getIsWarpSafe()
    {
        return $this->container['is_warp_safe'];
    }

    /**
     * Sets is_warp_safe
     * @param bool $is_warp_safe is_warp_safe boolean
     * @return $this
     */
    public function setIsWarpSafe($is_warp_safe)
    {
        $this->container['is_warp_safe'] = $is_warp_safe;

        return $this;
    }

    /**
     * Gets range_chance
     * @return bool
     */
    public function getRangeChance()
    {
        return $this->container['range_chance'];
    }

    /**
     * Sets range_chance
     * @param bool $range_chance range_chance boolean
     * @return $this
     */
    public function setRangeChance($range_chance)
    {
        $this->container['range_chance'] = $range_chance;

        return $this;
    }

    /**
     * Gets electronic_chance
     * @return bool
     */
    public function getElectronicChance()
    {
        return $this->container['electronic_chance'];
    }

    /**
     * Sets electronic_chance
     * @param bool $electronic_chance electronic_chance boolean
     * @return $this
     */
    public function setElectronicChance($electronic_chance)
    {
        $this->container['electronic_chance'] = $electronic_chance;

        return $this;
    }

    /**
     * Gets duration_attribute_id
     * @return int
     */
    public function getDurationAttributeId()
    {
        return $this->container['duration_attribute_id'];
    }

    /**
     * Sets duration_attribute_id
     * @param int $duration_attribute_id duration_attribute_id integer
     * @return $this
     */
    public function setDurationAttributeId($duration_attribute_id)
    {
        $this->container['duration_attribute_id'] = $duration_attribute_id;

        return $this;
    }

    /**
     * Gets tracking_speed_attribute_id
     * @return int
     */
    public function getTrackingSpeedAttributeId()
    {
        return $this->container['tracking_speed_attribute_id'];
    }

    /**
     * Sets tracking_speed_attribute_id
     * @param int $tracking_speed_attribute_id tracking_speed_attribute_id integer
     * @return $this
     */
    public function setTrackingSpeedAttributeId($tracking_speed_attribute_id)
    {
        $this->container['tracking_speed_attribute_id'] = $tracking_speed_attribute_id;

        return $this;
    }

    /**
     * Gets discharge_attribute_id
     * @return int
     */
    public function getDischargeAttributeId()
    {
        return $this->container['discharge_attribute_id'];
    }

    /**
     * Sets discharge_attribute_id
     * @param int $discharge_attribute_id discharge_attribute_id integer
     * @return $this
     */
    public function setDischargeAttributeId($discharge_attribute_id)
    {
        $this->container['discharge_attribute_id'] = $discharge_attribute_id;

        return $this;
    }

    /**
     * Gets range_attribute_id
     * @return int
     */
    public function getRangeAttributeId()
    {
        return $this->container['range_attribute_id'];
    }

    /**
     * Sets range_attribute_id
     * @param int $range_attribute_id range_attribute_id integer
     * @return $this
     */
    public function setRangeAttributeId($range_attribute_id)
    {
        $this->container['range_attribute_id'] = $range_attribute_id;

        return $this;
    }

    /**
     * Gets falloff_attribute_id
     * @return int
     */
    public function getFalloffAttributeId()
    {
        return $this->container['falloff_attribute_id'];
    }

    /**
     * Sets falloff_attribute_id
     * @param int $falloff_attribute_id falloff_attribute_id integer
     * @return $this
     */
    public function setFalloffAttributeId($falloff_attribute_id)
    {
        $this->container['falloff_attribute_id'] = $falloff_attribute_id;

        return $this;
    }

    /**
     * Gets modifiers
     * @return \Swagger\Client\Model\GetDogmaEffectsEffectIdOkModifiers[]
     */
    public function getModifiers()
    {
        return $this->container['modifiers'];
    }

    /**
     * Sets modifiers
     * @param \Swagger\Client\Model\GetDogmaEffectsEffectIdOkModifiers[] $modifiers modifiers array
     * @return $this
     */
    public function setModifiers($modifiers)
    {
        $this->container['modifiers'] = $modifiers;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


