<?php
/**
 * V2characterscharacterIdstatsModule
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.8.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;

/**
 * V2characterscharacterIdstatsModule Class Doc Comment
 *
 * @category    Class */
 // @description module object
/** 
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class V2characterscharacterIdstatsModule implements ArrayAccess
{
    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'v2characterscharacter_idstats_module';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = array(
        'activations_armor_hardener' => 'int',
        'activations_armor_repair_unit' => 'int',
        'activations_armor_resistance_shift_hardener' => 'int',
        'activations_automated_targeting_system' => 'int',
        'activations_bastion' => 'int',
        'activations_bomb_launcher' => 'int',
        'activations_capacitor_booster' => 'int',
        'activations_cargo_scanner' => 'int',
        'activations_cloaking_device' => 'int',
        'activations_clone_vat_bay' => 'int',
        'activations_cynosural_field' => 'int',
        'activations_damage_control' => 'int',
        'activations_data_miners' => 'int',
        'activations_drone_control_unit' => 'int',
        'activations_drone_tracking_modules' => 'int',
        'activations_eccm' => 'int',
        'activations_ecm' => 'int',
        'activations_ecm_burst' => 'int',
        'activations_energy_destabilizer' => 'int',
        'activations_energy_vampire' => 'int',
        'activations_energy_weapon' => 'int',
        'activations_festival_launcher' => 'int',
        'activations_frequency_mining_laser' => 'int',
        'activations_fueled_armor_repairer' => 'int',
        'activations_fueled_shield_booster' => 'int',
        'activations_gang_coordinator' => 'int',
        'activations_gas_cloud_harvester' => 'int',
        'activations_hull_repair_unit' => 'int',
        'activations_hybrid_weapon' => 'int',
        'activations_industrial_core' => 'int',
        'activations_interdiction_sphere_launcher' => 'int',
        'activations_micro_jump_drive' => 'int',
        'activations_mining_laser' => 'int',
        'activations_missile_launcher' => 'int',
        'activations_passive_targeting_system' => 'int',
        'activations_probe_launcher' => 'int',
        'activations_projected_eccm' => 'int',
        'activations_projectile_weapon' => 'int',
        'activations_propulsion_module' => 'int',
        'activations_remote_armor_repairer' => 'int',
        'activations_remote_capacitor_transmitter' => 'int',
        'activations_remote_ecm_burst' => 'int',
        'activations_remote_hull_repairer' => 'int',
        'activations_remote_sensor_booster' => 'int',
        'activations_remote_sensor_damper' => 'int',
        'activations_remote_shield_booster' => 'int',
        'activations_remote_tracking_computer' => 'int',
        'activations_salvager' => 'int',
        'activations_sensor_booster' => 'int',
        'activations_shield_booster' => 'int',
        'activations_shield_hardener' => 'int',
        'activations_ship_scanner' => 'int',
        'activations_siege' => 'int',
        'activations_smart_bomb' => 'int',
        'activations_stasis_web' => 'int',
        'activations_strip_miner' => 'int',
        'activations_super_weapon' => 'int',
        'activations_survey_scanner' => 'int',
        'activations_target_breaker' => 'int',
        'activations_target_painter' => 'int',
        'activations_tracking_computer' => 'int',
        'activations_tracking_disruptor' => 'int',
        'activations_tractor_beam' => 'int',
        'activations_triage' => 'int',
        'activations_warp_disrupt_field_generator' => 'int',
        'activations_warp_scrambler' => 'int',
        'link_weapons' => 'int',
        'overload' => 'int',
        'repairs' => 'int'
    );

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = array(
        'activations_armor_hardener' => 'activations_armor_hardener',
        'activations_armor_repair_unit' => 'activations_armor_repair_unit',
        'activations_armor_resistance_shift_hardener' => 'activations_armor_resistance_shift_hardener',
        'activations_automated_targeting_system' => 'activations_automated_targeting_system',
        'activations_bastion' => 'activations_bastion',
        'activations_bomb_launcher' => 'activations_bomb_launcher',
        'activations_capacitor_booster' => 'activations_capacitor_booster',
        'activations_cargo_scanner' => 'activations_cargo_scanner',
        'activations_cloaking_device' => 'activations_cloaking_device',
        'activations_clone_vat_bay' => 'activations_clone_vat_bay',
        'activations_cynosural_field' => 'activations_cynosural_field',
        'activations_damage_control' => 'activations_damage_control',
        'activations_data_miners' => 'activations_data_miners',
        'activations_drone_control_unit' => 'activations_drone_control_unit',
        'activations_drone_tracking_modules' => 'activations_drone_tracking_modules',
        'activations_eccm' => 'activations_eccm',
        'activations_ecm' => 'activations_ecm',
        'activations_ecm_burst' => 'activations_ecm_burst',
        'activations_energy_destabilizer' => 'activations_energy_destabilizer',
        'activations_energy_vampire' => 'activations_energy_vampire',
        'activations_energy_weapon' => 'activations_energy_weapon',
        'activations_festival_launcher' => 'activations_festival_launcher',
        'activations_frequency_mining_laser' => 'activations_frequency_mining_laser',
        'activations_fueled_armor_repairer' => 'activations_fueled_armor_repairer',
        'activations_fueled_shield_booster' => 'activations_fueled_shield_booster',
        'activations_gang_coordinator' => 'activations_gang_coordinator',
        'activations_gas_cloud_harvester' => 'activations_gas_cloud_harvester',
        'activations_hull_repair_unit' => 'activations_hull_repair_unit',
        'activations_hybrid_weapon' => 'activations_hybrid_weapon',
        'activations_industrial_core' => 'activations_industrial_core',
        'activations_interdiction_sphere_launcher' => 'activations_interdiction_sphere_launcher',
        'activations_micro_jump_drive' => 'activations_micro_jump_drive',
        'activations_mining_laser' => 'activations_mining_laser',
        'activations_missile_launcher' => 'activations_missile_launcher',
        'activations_passive_targeting_system' => 'activations_passive_targeting_system',
        'activations_probe_launcher' => 'activations_probe_launcher',
        'activations_projected_eccm' => 'activations_projected_eccm',
        'activations_projectile_weapon' => 'activations_projectile_weapon',
        'activations_propulsion_module' => 'activations_propulsion_module',
        'activations_remote_armor_repairer' => 'activations_remote_armor_repairer',
        'activations_remote_capacitor_transmitter' => 'activations_remote_capacitor_transmitter',
        'activations_remote_ecm_burst' => 'activations_remote_ecm_burst',
        'activations_remote_hull_repairer' => 'activations_remote_hull_repairer',
        'activations_remote_sensor_booster' => 'activations_remote_sensor_booster',
        'activations_remote_sensor_damper' => 'activations_remote_sensor_damper',
        'activations_remote_shield_booster' => 'activations_remote_shield_booster',
        'activations_remote_tracking_computer' => 'activations_remote_tracking_computer',
        'activations_salvager' => 'activations_salvager',
        'activations_sensor_booster' => 'activations_sensor_booster',
        'activations_shield_booster' => 'activations_shield_booster',
        'activations_shield_hardener' => 'activations_shield_hardener',
        'activations_ship_scanner' => 'activations_ship_scanner',
        'activations_siege' => 'activations_siege',
        'activations_smart_bomb' => 'activations_smart_bomb',
        'activations_stasis_web' => 'activations_stasis_web',
        'activations_strip_miner' => 'activations_strip_miner',
        'activations_super_weapon' => 'activations_super_weapon',
        'activations_survey_scanner' => 'activations_survey_scanner',
        'activations_target_breaker' => 'activations_target_breaker',
        'activations_target_painter' => 'activations_target_painter',
        'activations_tracking_computer' => 'activations_tracking_computer',
        'activations_tracking_disruptor' => 'activations_tracking_disruptor',
        'activations_tractor_beam' => 'activations_tractor_beam',
        'activations_triage' => 'activations_triage',
        'activations_warp_disrupt_field_generator' => 'activations_warp_disrupt_field_generator',
        'activations_warp_scrambler' => 'activations_warp_scrambler',
        'link_weapons' => 'link_weapons',
        'overload' => 'overload',
        'repairs' => 'repairs'
    );

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = array(
        'activations_armor_hardener' => 'setActivationsArmorHardener',
        'activations_armor_repair_unit' => 'setActivationsArmorRepairUnit',
        'activations_armor_resistance_shift_hardener' => 'setActivationsArmorResistanceShiftHardener',
        'activations_automated_targeting_system' => 'setActivationsAutomatedTargetingSystem',
        'activations_bastion' => 'setActivationsBastion',
        'activations_bomb_launcher' => 'setActivationsBombLauncher',
        'activations_capacitor_booster' => 'setActivationsCapacitorBooster',
        'activations_cargo_scanner' => 'setActivationsCargoScanner',
        'activations_cloaking_device' => 'setActivationsCloakingDevice',
        'activations_clone_vat_bay' => 'setActivationsCloneVatBay',
        'activations_cynosural_field' => 'setActivationsCynosuralField',
        'activations_damage_control' => 'setActivationsDamageControl',
        'activations_data_miners' => 'setActivationsDataMiners',
        'activations_drone_control_unit' => 'setActivationsDroneControlUnit',
        'activations_drone_tracking_modules' => 'setActivationsDroneTrackingModules',
        'activations_eccm' => 'setActivationsEccm',
        'activations_ecm' => 'setActivationsEcm',
        'activations_ecm_burst' => 'setActivationsEcmBurst',
        'activations_energy_destabilizer' => 'setActivationsEnergyDestabilizer',
        'activations_energy_vampire' => 'setActivationsEnergyVampire',
        'activations_energy_weapon' => 'setActivationsEnergyWeapon',
        'activations_festival_launcher' => 'setActivationsFestivalLauncher',
        'activations_frequency_mining_laser' => 'setActivationsFrequencyMiningLaser',
        'activations_fueled_armor_repairer' => 'setActivationsFueledArmorRepairer',
        'activations_fueled_shield_booster' => 'setActivationsFueledShieldBooster',
        'activations_gang_coordinator' => 'setActivationsGangCoordinator',
        'activations_gas_cloud_harvester' => 'setActivationsGasCloudHarvester',
        'activations_hull_repair_unit' => 'setActivationsHullRepairUnit',
        'activations_hybrid_weapon' => 'setActivationsHybridWeapon',
        'activations_industrial_core' => 'setActivationsIndustrialCore',
        'activations_interdiction_sphere_launcher' => 'setActivationsInterdictionSphereLauncher',
        'activations_micro_jump_drive' => 'setActivationsMicroJumpDrive',
        'activations_mining_laser' => 'setActivationsMiningLaser',
        'activations_missile_launcher' => 'setActivationsMissileLauncher',
        'activations_passive_targeting_system' => 'setActivationsPassiveTargetingSystem',
        'activations_probe_launcher' => 'setActivationsProbeLauncher',
        'activations_projected_eccm' => 'setActivationsProjectedEccm',
        'activations_projectile_weapon' => 'setActivationsProjectileWeapon',
        'activations_propulsion_module' => 'setActivationsPropulsionModule',
        'activations_remote_armor_repairer' => 'setActivationsRemoteArmorRepairer',
        'activations_remote_capacitor_transmitter' => 'setActivationsRemoteCapacitorTransmitter',
        'activations_remote_ecm_burst' => 'setActivationsRemoteEcmBurst',
        'activations_remote_hull_repairer' => 'setActivationsRemoteHullRepairer',
        'activations_remote_sensor_booster' => 'setActivationsRemoteSensorBooster',
        'activations_remote_sensor_damper' => 'setActivationsRemoteSensorDamper',
        'activations_remote_shield_booster' => 'setActivationsRemoteShieldBooster',
        'activations_remote_tracking_computer' => 'setActivationsRemoteTrackingComputer',
        'activations_salvager' => 'setActivationsSalvager',
        'activations_sensor_booster' => 'setActivationsSensorBooster',
        'activations_shield_booster' => 'setActivationsShieldBooster',
        'activations_shield_hardener' => 'setActivationsShieldHardener',
        'activations_ship_scanner' => 'setActivationsShipScanner',
        'activations_siege' => 'setActivationsSiege',
        'activations_smart_bomb' => 'setActivationsSmartBomb',
        'activations_stasis_web' => 'setActivationsStasisWeb',
        'activations_strip_miner' => 'setActivationsStripMiner',
        'activations_super_weapon' => 'setActivationsSuperWeapon',
        'activations_survey_scanner' => 'setActivationsSurveyScanner',
        'activations_target_breaker' => 'setActivationsTargetBreaker',
        'activations_target_painter' => 'setActivationsTargetPainter',
        'activations_tracking_computer' => 'setActivationsTrackingComputer',
        'activations_tracking_disruptor' => 'setActivationsTrackingDisruptor',
        'activations_tractor_beam' => 'setActivationsTractorBeam',
        'activations_triage' => 'setActivationsTriage',
        'activations_warp_disrupt_field_generator' => 'setActivationsWarpDisruptFieldGenerator',
        'activations_warp_scrambler' => 'setActivationsWarpScrambler',
        'link_weapons' => 'setLinkWeapons',
        'overload' => 'setOverload',
        'repairs' => 'setRepairs'
    );

    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = array(
        'activations_armor_hardener' => 'getActivationsArmorHardener',
        'activations_armor_repair_unit' => 'getActivationsArmorRepairUnit',
        'activations_armor_resistance_shift_hardener' => 'getActivationsArmorResistanceShiftHardener',
        'activations_automated_targeting_system' => 'getActivationsAutomatedTargetingSystem',
        'activations_bastion' => 'getActivationsBastion',
        'activations_bomb_launcher' => 'getActivationsBombLauncher',
        'activations_capacitor_booster' => 'getActivationsCapacitorBooster',
        'activations_cargo_scanner' => 'getActivationsCargoScanner',
        'activations_cloaking_device' => 'getActivationsCloakingDevice',
        'activations_clone_vat_bay' => 'getActivationsCloneVatBay',
        'activations_cynosural_field' => 'getActivationsCynosuralField',
        'activations_damage_control' => 'getActivationsDamageControl',
        'activations_data_miners' => 'getActivationsDataMiners',
        'activations_drone_control_unit' => 'getActivationsDroneControlUnit',
        'activations_drone_tracking_modules' => 'getActivationsDroneTrackingModules',
        'activations_eccm' => 'getActivationsEccm',
        'activations_ecm' => 'getActivationsEcm',
        'activations_ecm_burst' => 'getActivationsEcmBurst',
        'activations_energy_destabilizer' => 'getActivationsEnergyDestabilizer',
        'activations_energy_vampire' => 'getActivationsEnergyVampire',
        'activations_energy_weapon' => 'getActivationsEnergyWeapon',
        'activations_festival_launcher' => 'getActivationsFestivalLauncher',
        'activations_frequency_mining_laser' => 'getActivationsFrequencyMiningLaser',
        'activations_fueled_armor_repairer' => 'getActivationsFueledArmorRepairer',
        'activations_fueled_shield_booster' => 'getActivationsFueledShieldBooster',
        'activations_gang_coordinator' => 'getActivationsGangCoordinator',
        'activations_gas_cloud_harvester' => 'getActivationsGasCloudHarvester',
        'activations_hull_repair_unit' => 'getActivationsHullRepairUnit',
        'activations_hybrid_weapon' => 'getActivationsHybridWeapon',
        'activations_industrial_core' => 'getActivationsIndustrialCore',
        'activations_interdiction_sphere_launcher' => 'getActivationsInterdictionSphereLauncher',
        'activations_micro_jump_drive' => 'getActivationsMicroJumpDrive',
        'activations_mining_laser' => 'getActivationsMiningLaser',
        'activations_missile_launcher' => 'getActivationsMissileLauncher',
        'activations_passive_targeting_system' => 'getActivationsPassiveTargetingSystem',
        'activations_probe_launcher' => 'getActivationsProbeLauncher',
        'activations_projected_eccm' => 'getActivationsProjectedEccm',
        'activations_projectile_weapon' => 'getActivationsProjectileWeapon',
        'activations_propulsion_module' => 'getActivationsPropulsionModule',
        'activations_remote_armor_repairer' => 'getActivationsRemoteArmorRepairer',
        'activations_remote_capacitor_transmitter' => 'getActivationsRemoteCapacitorTransmitter',
        'activations_remote_ecm_burst' => 'getActivationsRemoteEcmBurst',
        'activations_remote_hull_repairer' => 'getActivationsRemoteHullRepairer',
        'activations_remote_sensor_booster' => 'getActivationsRemoteSensorBooster',
        'activations_remote_sensor_damper' => 'getActivationsRemoteSensorDamper',
        'activations_remote_shield_booster' => 'getActivationsRemoteShieldBooster',
        'activations_remote_tracking_computer' => 'getActivationsRemoteTrackingComputer',
        'activations_salvager' => 'getActivationsSalvager',
        'activations_sensor_booster' => 'getActivationsSensorBooster',
        'activations_shield_booster' => 'getActivationsShieldBooster',
        'activations_shield_hardener' => 'getActivationsShieldHardener',
        'activations_ship_scanner' => 'getActivationsShipScanner',
        'activations_siege' => 'getActivationsSiege',
        'activations_smart_bomb' => 'getActivationsSmartBomb',
        'activations_stasis_web' => 'getActivationsStasisWeb',
        'activations_strip_miner' => 'getActivationsStripMiner',
        'activations_super_weapon' => 'getActivationsSuperWeapon',
        'activations_survey_scanner' => 'getActivationsSurveyScanner',
        'activations_target_breaker' => 'getActivationsTargetBreaker',
        'activations_target_painter' => 'getActivationsTargetPainter',
        'activations_tracking_computer' => 'getActivationsTrackingComputer',
        'activations_tracking_disruptor' => 'getActivationsTrackingDisruptor',
        'activations_tractor_beam' => 'getActivationsTractorBeam',
        'activations_triage' => 'getActivationsTriage',
        'activations_warp_disrupt_field_generator' => 'getActivationsWarpDisruptFieldGenerator',
        'activations_warp_scrambler' => 'getActivationsWarpScrambler',
        'link_weapons' => 'getLinkWeapons',
        'overload' => 'getOverload',
        'repairs' => 'getRepairs'
    );

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = array();

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['activations_armor_hardener'] = isset($data['activations_armor_hardener']) ? $data['activations_armor_hardener'] : null;
        $this->container['activations_armor_repair_unit'] = isset($data['activations_armor_repair_unit']) ? $data['activations_armor_repair_unit'] : null;
        $this->container['activations_armor_resistance_shift_hardener'] = isset($data['activations_armor_resistance_shift_hardener']) ? $data['activations_armor_resistance_shift_hardener'] : null;
        $this->container['activations_automated_targeting_system'] = isset($data['activations_automated_targeting_system']) ? $data['activations_automated_targeting_system'] : null;
        $this->container['activations_bastion'] = isset($data['activations_bastion']) ? $data['activations_bastion'] : null;
        $this->container['activations_bomb_launcher'] = isset($data['activations_bomb_launcher']) ? $data['activations_bomb_launcher'] : null;
        $this->container['activations_capacitor_booster'] = isset($data['activations_capacitor_booster']) ? $data['activations_capacitor_booster'] : null;
        $this->container['activations_cargo_scanner'] = isset($data['activations_cargo_scanner']) ? $data['activations_cargo_scanner'] : null;
        $this->container['activations_cloaking_device'] = isset($data['activations_cloaking_device']) ? $data['activations_cloaking_device'] : null;
        $this->container['activations_clone_vat_bay'] = isset($data['activations_clone_vat_bay']) ? $data['activations_clone_vat_bay'] : null;
        $this->container['activations_cynosural_field'] = isset($data['activations_cynosural_field']) ? $data['activations_cynosural_field'] : null;
        $this->container['activations_damage_control'] = isset($data['activations_damage_control']) ? $data['activations_damage_control'] : null;
        $this->container['activations_data_miners'] = isset($data['activations_data_miners']) ? $data['activations_data_miners'] : null;
        $this->container['activations_drone_control_unit'] = isset($data['activations_drone_control_unit']) ? $data['activations_drone_control_unit'] : null;
        $this->container['activations_drone_tracking_modules'] = isset($data['activations_drone_tracking_modules']) ? $data['activations_drone_tracking_modules'] : null;
        $this->container['activations_eccm'] = isset($data['activations_eccm']) ? $data['activations_eccm'] : null;
        $this->container['activations_ecm'] = isset($data['activations_ecm']) ? $data['activations_ecm'] : null;
        $this->container['activations_ecm_burst'] = isset($data['activations_ecm_burst']) ? $data['activations_ecm_burst'] : null;
        $this->container['activations_energy_destabilizer'] = isset($data['activations_energy_destabilizer']) ? $data['activations_energy_destabilizer'] : null;
        $this->container['activations_energy_vampire'] = isset($data['activations_energy_vampire']) ? $data['activations_energy_vampire'] : null;
        $this->container['activations_energy_weapon'] = isset($data['activations_energy_weapon']) ? $data['activations_energy_weapon'] : null;
        $this->container['activations_festival_launcher'] = isset($data['activations_festival_launcher']) ? $data['activations_festival_launcher'] : null;
        $this->container['activations_frequency_mining_laser'] = isset($data['activations_frequency_mining_laser']) ? $data['activations_frequency_mining_laser'] : null;
        $this->container['activations_fueled_armor_repairer'] = isset($data['activations_fueled_armor_repairer']) ? $data['activations_fueled_armor_repairer'] : null;
        $this->container['activations_fueled_shield_booster'] = isset($data['activations_fueled_shield_booster']) ? $data['activations_fueled_shield_booster'] : null;
        $this->container['activations_gang_coordinator'] = isset($data['activations_gang_coordinator']) ? $data['activations_gang_coordinator'] : null;
        $this->container['activations_gas_cloud_harvester'] = isset($data['activations_gas_cloud_harvester']) ? $data['activations_gas_cloud_harvester'] : null;
        $this->container['activations_hull_repair_unit'] = isset($data['activations_hull_repair_unit']) ? $data['activations_hull_repair_unit'] : null;
        $this->container['activations_hybrid_weapon'] = isset($data['activations_hybrid_weapon']) ? $data['activations_hybrid_weapon'] : null;
        $this->container['activations_industrial_core'] = isset($data['activations_industrial_core']) ? $data['activations_industrial_core'] : null;
        $this->container['activations_interdiction_sphere_launcher'] = isset($data['activations_interdiction_sphere_launcher']) ? $data['activations_interdiction_sphere_launcher'] : null;
        $this->container['activations_micro_jump_drive'] = isset($data['activations_micro_jump_drive']) ? $data['activations_micro_jump_drive'] : null;
        $this->container['activations_mining_laser'] = isset($data['activations_mining_laser']) ? $data['activations_mining_laser'] : null;
        $this->container['activations_missile_launcher'] = isset($data['activations_missile_launcher']) ? $data['activations_missile_launcher'] : null;
        $this->container['activations_passive_targeting_system'] = isset($data['activations_passive_targeting_system']) ? $data['activations_passive_targeting_system'] : null;
        $this->container['activations_probe_launcher'] = isset($data['activations_probe_launcher']) ? $data['activations_probe_launcher'] : null;
        $this->container['activations_projected_eccm'] = isset($data['activations_projected_eccm']) ? $data['activations_projected_eccm'] : null;
        $this->container['activations_projectile_weapon'] = isset($data['activations_projectile_weapon']) ? $data['activations_projectile_weapon'] : null;
        $this->container['activations_propulsion_module'] = isset($data['activations_propulsion_module']) ? $data['activations_propulsion_module'] : null;
        $this->container['activations_remote_armor_repairer'] = isset($data['activations_remote_armor_repairer']) ? $data['activations_remote_armor_repairer'] : null;
        $this->container['activations_remote_capacitor_transmitter'] = isset($data['activations_remote_capacitor_transmitter']) ? $data['activations_remote_capacitor_transmitter'] : null;
        $this->container['activations_remote_ecm_burst'] = isset($data['activations_remote_ecm_burst']) ? $data['activations_remote_ecm_burst'] : null;
        $this->container['activations_remote_hull_repairer'] = isset($data['activations_remote_hull_repairer']) ? $data['activations_remote_hull_repairer'] : null;
        $this->container['activations_remote_sensor_booster'] = isset($data['activations_remote_sensor_booster']) ? $data['activations_remote_sensor_booster'] : null;
        $this->container['activations_remote_sensor_damper'] = isset($data['activations_remote_sensor_damper']) ? $data['activations_remote_sensor_damper'] : null;
        $this->container['activations_remote_shield_booster'] = isset($data['activations_remote_shield_booster']) ? $data['activations_remote_shield_booster'] : null;
        $this->container['activations_remote_tracking_computer'] = isset($data['activations_remote_tracking_computer']) ? $data['activations_remote_tracking_computer'] : null;
        $this->container['activations_salvager'] = isset($data['activations_salvager']) ? $data['activations_salvager'] : null;
        $this->container['activations_sensor_booster'] = isset($data['activations_sensor_booster']) ? $data['activations_sensor_booster'] : null;
        $this->container['activations_shield_booster'] = isset($data['activations_shield_booster']) ? $data['activations_shield_booster'] : null;
        $this->container['activations_shield_hardener'] = isset($data['activations_shield_hardener']) ? $data['activations_shield_hardener'] : null;
        $this->container['activations_ship_scanner'] = isset($data['activations_ship_scanner']) ? $data['activations_ship_scanner'] : null;
        $this->container['activations_siege'] = isset($data['activations_siege']) ? $data['activations_siege'] : null;
        $this->container['activations_smart_bomb'] = isset($data['activations_smart_bomb']) ? $data['activations_smart_bomb'] : null;
        $this->container['activations_stasis_web'] = isset($data['activations_stasis_web']) ? $data['activations_stasis_web'] : null;
        $this->container['activations_strip_miner'] = isset($data['activations_strip_miner']) ? $data['activations_strip_miner'] : null;
        $this->container['activations_super_weapon'] = isset($data['activations_super_weapon']) ? $data['activations_super_weapon'] : null;
        $this->container['activations_survey_scanner'] = isset($data['activations_survey_scanner']) ? $data['activations_survey_scanner'] : null;
        $this->container['activations_target_breaker'] = isset($data['activations_target_breaker']) ? $data['activations_target_breaker'] : null;
        $this->container['activations_target_painter'] = isset($data['activations_target_painter']) ? $data['activations_target_painter'] : null;
        $this->container['activations_tracking_computer'] = isset($data['activations_tracking_computer']) ? $data['activations_tracking_computer'] : null;
        $this->container['activations_tracking_disruptor'] = isset($data['activations_tracking_disruptor']) ? $data['activations_tracking_disruptor'] : null;
        $this->container['activations_tractor_beam'] = isset($data['activations_tractor_beam']) ? $data['activations_tractor_beam'] : null;
        $this->container['activations_triage'] = isset($data['activations_triage']) ? $data['activations_triage'] : null;
        $this->container['activations_warp_disrupt_field_generator'] = isset($data['activations_warp_disrupt_field_generator']) ? $data['activations_warp_disrupt_field_generator'] : null;
        $this->container['activations_warp_scrambler'] = isset($data['activations_warp_scrambler']) ? $data['activations_warp_scrambler'] : null;
        $this->container['link_weapons'] = isset($data['link_weapons']) ? $data['link_weapons'] : null;
        $this->container['overload'] = isset($data['overload']) ? $data['overload'] : null;
        $this->container['repairs'] = isset($data['repairs']) ? $data['repairs'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = array();
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properteis are valid
     */
    public function valid()
    {
        return true;
    }


    /**
     * Gets activations_armor_hardener
     * @return int
     */
    public function getActivationsArmorHardener()
    {
        return $this->container['activations_armor_hardener'];
    }

    /**
     * Sets activations_armor_hardener
     * @param int $activations_armor_hardener activations_armor_hardener integer
     * @return $this
     */
    public function setActivationsArmorHardener($activations_armor_hardener)
    {
        $this->container['activations_armor_hardener'] = $activations_armor_hardener;

        return $this;
    }

    /**
     * Gets activations_armor_repair_unit
     * @return int
     */
    public function getActivationsArmorRepairUnit()
    {
        return $this->container['activations_armor_repair_unit'];
    }

    /**
     * Sets activations_armor_repair_unit
     * @param int $activations_armor_repair_unit activations_armor_repair_unit integer
     * @return $this
     */
    public function setActivationsArmorRepairUnit($activations_armor_repair_unit)
    {
        $this->container['activations_armor_repair_unit'] = $activations_armor_repair_unit;

        return $this;
    }

    /**
     * Gets activations_armor_resistance_shift_hardener
     * @return int
     */
    public function getActivationsArmorResistanceShiftHardener()
    {
        return $this->container['activations_armor_resistance_shift_hardener'];
    }

    /**
     * Sets activations_armor_resistance_shift_hardener
     * @param int $activations_armor_resistance_shift_hardener activations_armor_resistance_shift_hardener integer
     * @return $this
     */
    public function setActivationsArmorResistanceShiftHardener($activations_armor_resistance_shift_hardener)
    {
        $this->container['activations_armor_resistance_shift_hardener'] = $activations_armor_resistance_shift_hardener;

        return $this;
    }

    /**
     * Gets activations_automated_targeting_system
     * @return int
     */
    public function getActivationsAutomatedTargetingSystem()
    {
        return $this->container['activations_automated_targeting_system'];
    }

    /**
     * Sets activations_automated_targeting_system
     * @param int $activations_automated_targeting_system activations_automated_targeting_system integer
     * @return $this
     */
    public function setActivationsAutomatedTargetingSystem($activations_automated_targeting_system)
    {
        $this->container['activations_automated_targeting_system'] = $activations_automated_targeting_system;

        return $this;
    }

    /**
     * Gets activations_bastion
     * @return int
     */
    public function getActivationsBastion()
    {
        return $this->container['activations_bastion'];
    }

    /**
     * Sets activations_bastion
     * @param int $activations_bastion activations_bastion integer
     * @return $this
     */
    public function setActivationsBastion($activations_bastion)
    {
        $this->container['activations_bastion'] = $activations_bastion;

        return $this;
    }

    /**
     * Gets activations_bomb_launcher
     * @return int
     */
    public function getActivationsBombLauncher()
    {
        return $this->container['activations_bomb_launcher'];
    }

    /**
     * Sets activations_bomb_launcher
     * @param int $activations_bomb_launcher activations_bomb_launcher integer
     * @return $this
     */
    public function setActivationsBombLauncher($activations_bomb_launcher)
    {
        $this->container['activations_bomb_launcher'] = $activations_bomb_launcher;

        return $this;
    }

    /**
     * Gets activations_capacitor_booster
     * @return int
     */
    public function getActivationsCapacitorBooster()
    {
        return $this->container['activations_capacitor_booster'];
    }

    /**
     * Sets activations_capacitor_booster
     * @param int $activations_capacitor_booster activations_capacitor_booster integer
     * @return $this
     */
    public function setActivationsCapacitorBooster($activations_capacitor_booster)
    {
        $this->container['activations_capacitor_booster'] = $activations_capacitor_booster;

        return $this;
    }

    /**
     * Gets activations_cargo_scanner
     * @return int
     */
    public function getActivationsCargoScanner()
    {
        return $this->container['activations_cargo_scanner'];
    }

    /**
     * Sets activations_cargo_scanner
     * @param int $activations_cargo_scanner activations_cargo_scanner integer
     * @return $this
     */
    public function setActivationsCargoScanner($activations_cargo_scanner)
    {
        $this->container['activations_cargo_scanner'] = $activations_cargo_scanner;

        return $this;
    }

    /**
     * Gets activations_cloaking_device
     * @return int
     */
    public function getActivationsCloakingDevice()
    {
        return $this->container['activations_cloaking_device'];
    }

    /**
     * Sets activations_cloaking_device
     * @param int $activations_cloaking_device activations_cloaking_device integer
     * @return $this
     */
    public function setActivationsCloakingDevice($activations_cloaking_device)
    {
        $this->container['activations_cloaking_device'] = $activations_cloaking_device;

        return $this;
    }

    /**
     * Gets activations_clone_vat_bay
     * @return int
     */
    public function getActivationsCloneVatBay()
    {
        return $this->container['activations_clone_vat_bay'];
    }

    /**
     * Sets activations_clone_vat_bay
     * @param int $activations_clone_vat_bay activations_clone_vat_bay integer
     * @return $this
     */
    public function setActivationsCloneVatBay($activations_clone_vat_bay)
    {
        $this->container['activations_clone_vat_bay'] = $activations_clone_vat_bay;

        return $this;
    }

    /**
     * Gets activations_cynosural_field
     * @return int
     */
    public function getActivationsCynosuralField()
    {
        return $this->container['activations_cynosural_field'];
    }

    /**
     * Sets activations_cynosural_field
     * @param int $activations_cynosural_field activations_cynosural_field integer
     * @return $this
     */
    public function setActivationsCynosuralField($activations_cynosural_field)
    {
        $this->container['activations_cynosural_field'] = $activations_cynosural_field;

        return $this;
    }

    /**
     * Gets activations_damage_control
     * @return int
     */
    public function getActivationsDamageControl()
    {
        return $this->container['activations_damage_control'];
    }

    /**
     * Sets activations_damage_control
     * @param int $activations_damage_control activations_damage_control integer
     * @return $this
     */
    public function setActivationsDamageControl($activations_damage_control)
    {
        $this->container['activations_damage_control'] = $activations_damage_control;

        return $this;
    }

    /**
     * Gets activations_data_miners
     * @return int
     */
    public function getActivationsDataMiners()
    {
        return $this->container['activations_data_miners'];
    }

    /**
     * Sets activations_data_miners
     * @param int $activations_data_miners activations_data_miners integer
     * @return $this
     */
    public function setActivationsDataMiners($activations_data_miners)
    {
        $this->container['activations_data_miners'] = $activations_data_miners;

        return $this;
    }

    /**
     * Gets activations_drone_control_unit
     * @return int
     */
    public function getActivationsDroneControlUnit()
    {
        return $this->container['activations_drone_control_unit'];
    }

    /**
     * Sets activations_drone_control_unit
     * @param int $activations_drone_control_unit activations_drone_control_unit integer
     * @return $this
     */
    public function setActivationsDroneControlUnit($activations_drone_control_unit)
    {
        $this->container['activations_drone_control_unit'] = $activations_drone_control_unit;

        return $this;
    }

    /**
     * Gets activations_drone_tracking_modules
     * @return int
     */
    public function getActivationsDroneTrackingModules()
    {
        return $this->container['activations_drone_tracking_modules'];
    }

    /**
     * Sets activations_drone_tracking_modules
     * @param int $activations_drone_tracking_modules activations_drone_tracking_modules integer
     * @return $this
     */
    public function setActivationsDroneTrackingModules($activations_drone_tracking_modules)
    {
        $this->container['activations_drone_tracking_modules'] = $activations_drone_tracking_modules;

        return $this;
    }

    /**
     * Gets activations_eccm
     * @return int
     */
    public function getActivationsEccm()
    {
        return $this->container['activations_eccm'];
    }

    /**
     * Sets activations_eccm
     * @param int $activations_eccm activations_eccm integer
     * @return $this
     */
    public function setActivationsEccm($activations_eccm)
    {
        $this->container['activations_eccm'] = $activations_eccm;

        return $this;
    }

    /**
     * Gets activations_ecm
     * @return int
     */
    public function getActivationsEcm()
    {
        return $this->container['activations_ecm'];
    }

    /**
     * Sets activations_ecm
     * @param int $activations_ecm activations_ecm integer
     * @return $this
     */
    public function setActivationsEcm($activations_ecm)
    {
        $this->container['activations_ecm'] = $activations_ecm;

        return $this;
    }

    /**
     * Gets activations_ecm_burst
     * @return int
     */
    public function getActivationsEcmBurst()
    {
        return $this->container['activations_ecm_burst'];
    }

    /**
     * Sets activations_ecm_burst
     * @param int $activations_ecm_burst activations_ecm_burst integer
     * @return $this
     */
    public function setActivationsEcmBurst($activations_ecm_burst)
    {
        $this->container['activations_ecm_burst'] = $activations_ecm_burst;

        return $this;
    }

    /**
     * Gets activations_energy_destabilizer
     * @return int
     */
    public function getActivationsEnergyDestabilizer()
    {
        return $this->container['activations_energy_destabilizer'];
    }

    /**
     * Sets activations_energy_destabilizer
     * @param int $activations_energy_destabilizer activations_energy_destabilizer integer
     * @return $this
     */
    public function setActivationsEnergyDestabilizer($activations_energy_destabilizer)
    {
        $this->container['activations_energy_destabilizer'] = $activations_energy_destabilizer;

        return $this;
    }

    /**
     * Gets activations_energy_vampire
     * @return int
     */
    public function getActivationsEnergyVampire()
    {
        return $this->container['activations_energy_vampire'];
    }

    /**
     * Sets activations_energy_vampire
     * @param int $activations_energy_vampire activations_energy_vampire integer
     * @return $this
     */
    public function setActivationsEnergyVampire($activations_energy_vampire)
    {
        $this->container['activations_energy_vampire'] = $activations_energy_vampire;

        return $this;
    }

    /**
     * Gets activations_energy_weapon
     * @return int
     */
    public function getActivationsEnergyWeapon()
    {
        return $this->container['activations_energy_weapon'];
    }

    /**
     * Sets activations_energy_weapon
     * @param int $activations_energy_weapon activations_energy_weapon integer
     * @return $this
     */
    public function setActivationsEnergyWeapon($activations_energy_weapon)
    {
        $this->container['activations_energy_weapon'] = $activations_energy_weapon;

        return $this;
    }

    /**
     * Gets activations_festival_launcher
     * @return int
     */
    public function getActivationsFestivalLauncher()
    {
        return $this->container['activations_festival_launcher'];
    }

    /**
     * Sets activations_festival_launcher
     * @param int $activations_festival_launcher activations_festival_launcher integer
     * @return $this
     */
    public function setActivationsFestivalLauncher($activations_festival_launcher)
    {
        $this->container['activations_festival_launcher'] = $activations_festival_launcher;

        return $this;
    }

    /**
     * Gets activations_frequency_mining_laser
     * @return int
     */
    public function getActivationsFrequencyMiningLaser()
    {
        return $this->container['activations_frequency_mining_laser'];
    }

    /**
     * Sets activations_frequency_mining_laser
     * @param int $activations_frequency_mining_laser activations_frequency_mining_laser integer
     * @return $this
     */
    public function setActivationsFrequencyMiningLaser($activations_frequency_mining_laser)
    {
        $this->container['activations_frequency_mining_laser'] = $activations_frequency_mining_laser;

        return $this;
    }

    /**
     * Gets activations_fueled_armor_repairer
     * @return int
     */
    public function getActivationsFueledArmorRepairer()
    {
        return $this->container['activations_fueled_armor_repairer'];
    }

    /**
     * Sets activations_fueled_armor_repairer
     * @param int $activations_fueled_armor_repairer activations_fueled_armor_repairer integer
     * @return $this
     */
    public function setActivationsFueledArmorRepairer($activations_fueled_armor_repairer)
    {
        $this->container['activations_fueled_armor_repairer'] = $activations_fueled_armor_repairer;

        return $this;
    }

    /**
     * Gets activations_fueled_shield_booster
     * @return int
     */
    public function getActivationsFueledShieldBooster()
    {
        return $this->container['activations_fueled_shield_booster'];
    }

    /**
     * Sets activations_fueled_shield_booster
     * @param int $activations_fueled_shield_booster activations_fueled_shield_booster integer
     * @return $this
     */
    public function setActivationsFueledShieldBooster($activations_fueled_shield_booster)
    {
        $this->container['activations_fueled_shield_booster'] = $activations_fueled_shield_booster;

        return $this;
    }

    /**
     * Gets activations_gang_coordinator
     * @return int
     */
    public function getActivationsGangCoordinator()
    {
        return $this->container['activations_gang_coordinator'];
    }

    /**
     * Sets activations_gang_coordinator
     * @param int $activations_gang_coordinator activations_gang_coordinator integer
     * @return $this
     */
    public function setActivationsGangCoordinator($activations_gang_coordinator)
    {
        $this->container['activations_gang_coordinator'] = $activations_gang_coordinator;

        return $this;
    }

    /**
     * Gets activations_gas_cloud_harvester
     * @return int
     */
    public function getActivationsGasCloudHarvester()
    {
        return $this->container['activations_gas_cloud_harvester'];
    }

    /**
     * Sets activations_gas_cloud_harvester
     * @param int $activations_gas_cloud_harvester activations_gas_cloud_harvester integer
     * @return $this
     */
    public function setActivationsGasCloudHarvester($activations_gas_cloud_harvester)
    {
        $this->container['activations_gas_cloud_harvester'] = $activations_gas_cloud_harvester;

        return $this;
    }

    /**
     * Gets activations_hull_repair_unit
     * @return int
     */
    public function getActivationsHullRepairUnit()
    {
        return $this->container['activations_hull_repair_unit'];
    }

    /**
     * Sets activations_hull_repair_unit
     * @param int $activations_hull_repair_unit activations_hull_repair_unit integer
     * @return $this
     */
    public function setActivationsHullRepairUnit($activations_hull_repair_unit)
    {
        $this->container['activations_hull_repair_unit'] = $activations_hull_repair_unit;

        return $this;
    }

    /**
     * Gets activations_hybrid_weapon
     * @return int
     */
    public function getActivationsHybridWeapon()
    {
        return $this->container['activations_hybrid_weapon'];
    }

    /**
     * Sets activations_hybrid_weapon
     * @param int $activations_hybrid_weapon activations_hybrid_weapon integer
     * @return $this
     */
    public function setActivationsHybridWeapon($activations_hybrid_weapon)
    {
        $this->container['activations_hybrid_weapon'] = $activations_hybrid_weapon;

        return $this;
    }

    /**
     * Gets activations_industrial_core
     * @return int
     */
    public function getActivationsIndustrialCore()
    {
        return $this->container['activations_industrial_core'];
    }

    /**
     * Sets activations_industrial_core
     * @param int $activations_industrial_core activations_industrial_core integer
     * @return $this
     */
    public function setActivationsIndustrialCore($activations_industrial_core)
    {
        $this->container['activations_industrial_core'] = $activations_industrial_core;

        return $this;
    }

    /**
     * Gets activations_interdiction_sphere_launcher
     * @return int
     */
    public function getActivationsInterdictionSphereLauncher()
    {
        return $this->container['activations_interdiction_sphere_launcher'];
    }

    /**
     * Sets activations_interdiction_sphere_launcher
     * @param int $activations_interdiction_sphere_launcher activations_interdiction_sphere_launcher integer
     * @return $this
     */
    public function setActivationsInterdictionSphereLauncher($activations_interdiction_sphere_launcher)
    {
        $this->container['activations_interdiction_sphere_launcher'] = $activations_interdiction_sphere_launcher;

        return $this;
    }

    /**
     * Gets activations_micro_jump_drive
     * @return int
     */
    public function getActivationsMicroJumpDrive()
    {
        return $this->container['activations_micro_jump_drive'];
    }

    /**
     * Sets activations_micro_jump_drive
     * @param int $activations_micro_jump_drive activations_micro_jump_drive integer
     * @return $this
     */
    public function setActivationsMicroJumpDrive($activations_micro_jump_drive)
    {
        $this->container['activations_micro_jump_drive'] = $activations_micro_jump_drive;

        return $this;
    }

    /**
     * Gets activations_mining_laser
     * @return int
     */
    public function getActivationsMiningLaser()
    {
        return $this->container['activations_mining_laser'];
    }

    /**
     * Sets activations_mining_laser
     * @param int $activations_mining_laser activations_mining_laser integer
     * @return $this
     */
    public function setActivationsMiningLaser($activations_mining_laser)
    {
        $this->container['activations_mining_laser'] = $activations_mining_laser;

        return $this;
    }

    /**
     * Gets activations_missile_launcher
     * @return int
     */
    public function getActivationsMissileLauncher()
    {
        return $this->container['activations_missile_launcher'];
    }

    /**
     * Sets activations_missile_launcher
     * @param int $activations_missile_launcher activations_missile_launcher integer
     * @return $this
     */
    public function setActivationsMissileLauncher($activations_missile_launcher)
    {
        $this->container['activations_missile_launcher'] = $activations_missile_launcher;

        return $this;
    }

    /**
     * Gets activations_passive_targeting_system
     * @return int
     */
    public function getActivationsPassiveTargetingSystem()
    {
        return $this->container['activations_passive_targeting_system'];
    }

    /**
     * Sets activations_passive_targeting_system
     * @param int $activations_passive_targeting_system activations_passive_targeting_system integer
     * @return $this
     */
    public function setActivationsPassiveTargetingSystem($activations_passive_targeting_system)
    {
        $this->container['activations_passive_targeting_system'] = $activations_passive_targeting_system;

        return $this;
    }

    /**
     * Gets activations_probe_launcher
     * @return int
     */
    public function getActivationsProbeLauncher()
    {
        return $this->container['activations_probe_launcher'];
    }

    /**
     * Sets activations_probe_launcher
     * @param int $activations_probe_launcher activations_probe_launcher integer
     * @return $this
     */
    public function setActivationsProbeLauncher($activations_probe_launcher)
    {
        $this->container['activations_probe_launcher'] = $activations_probe_launcher;

        return $this;
    }

    /**
     * Gets activations_projected_eccm
     * @return int
     */
    public function getActivationsProjectedEccm()
    {
        return $this->container['activations_projected_eccm'];
    }

    /**
     * Sets activations_projected_eccm
     * @param int $activations_projected_eccm activations_projected_eccm integer
     * @return $this
     */
    public function setActivationsProjectedEccm($activations_projected_eccm)
    {
        $this->container['activations_projected_eccm'] = $activations_projected_eccm;

        return $this;
    }

    /**
     * Gets activations_projectile_weapon
     * @return int
     */
    public function getActivationsProjectileWeapon()
    {
        return $this->container['activations_projectile_weapon'];
    }

    /**
     * Sets activations_projectile_weapon
     * @param int $activations_projectile_weapon activations_projectile_weapon integer
     * @return $this
     */
    public function setActivationsProjectileWeapon($activations_projectile_weapon)
    {
        $this->container['activations_projectile_weapon'] = $activations_projectile_weapon;

        return $this;
    }

    /**
     * Gets activations_propulsion_module
     * @return int
     */
    public function getActivationsPropulsionModule()
    {
        return $this->container['activations_propulsion_module'];
    }

    /**
     * Sets activations_propulsion_module
     * @param int $activations_propulsion_module activations_propulsion_module integer
     * @return $this
     */
    public function setActivationsPropulsionModule($activations_propulsion_module)
    {
        $this->container['activations_propulsion_module'] = $activations_propulsion_module;

        return $this;
    }

    /**
     * Gets activations_remote_armor_repairer
     * @return int
     */
    public function getActivationsRemoteArmorRepairer()
    {
        return $this->container['activations_remote_armor_repairer'];
    }

    /**
     * Sets activations_remote_armor_repairer
     * @param int $activations_remote_armor_repairer activations_remote_armor_repairer integer
     * @return $this
     */
    public function setActivationsRemoteArmorRepairer($activations_remote_armor_repairer)
    {
        $this->container['activations_remote_armor_repairer'] = $activations_remote_armor_repairer;

        return $this;
    }

    /**
     * Gets activations_remote_capacitor_transmitter
     * @return int
     */
    public function getActivationsRemoteCapacitorTransmitter()
    {
        return $this->container['activations_remote_capacitor_transmitter'];
    }

    /**
     * Sets activations_remote_capacitor_transmitter
     * @param int $activations_remote_capacitor_transmitter activations_remote_capacitor_transmitter integer
     * @return $this
     */
    public function setActivationsRemoteCapacitorTransmitter($activations_remote_capacitor_transmitter)
    {
        $this->container['activations_remote_capacitor_transmitter'] = $activations_remote_capacitor_transmitter;

        return $this;
    }

    /**
     * Gets activations_remote_ecm_burst
     * @return int
     */
    public function getActivationsRemoteEcmBurst()
    {
        return $this->container['activations_remote_ecm_burst'];
    }

    /**
     * Sets activations_remote_ecm_burst
     * @param int $activations_remote_ecm_burst activations_remote_ecm_burst integer
     * @return $this
     */
    public function setActivationsRemoteEcmBurst($activations_remote_ecm_burst)
    {
        $this->container['activations_remote_ecm_burst'] = $activations_remote_ecm_burst;

        return $this;
    }

    /**
     * Gets activations_remote_hull_repairer
     * @return int
     */
    public function getActivationsRemoteHullRepairer()
    {
        return $this->container['activations_remote_hull_repairer'];
    }

    /**
     * Sets activations_remote_hull_repairer
     * @param int $activations_remote_hull_repairer activations_remote_hull_repairer integer
     * @return $this
     */
    public function setActivationsRemoteHullRepairer($activations_remote_hull_repairer)
    {
        $this->container['activations_remote_hull_repairer'] = $activations_remote_hull_repairer;

        return $this;
    }

    /**
     * Gets activations_remote_sensor_booster
     * @return int
     */
    public function getActivationsRemoteSensorBooster()
    {
        return $this->container['activations_remote_sensor_booster'];
    }

    /**
     * Sets activations_remote_sensor_booster
     * @param int $activations_remote_sensor_booster activations_remote_sensor_booster integer
     * @return $this
     */
    public function setActivationsRemoteSensorBooster($activations_remote_sensor_booster)
    {
        $this->container['activations_remote_sensor_booster'] = $activations_remote_sensor_booster;

        return $this;
    }

    /**
     * Gets activations_remote_sensor_damper
     * @return int
     */
    public function getActivationsRemoteSensorDamper()
    {
        return $this->container['activations_remote_sensor_damper'];
    }

    /**
     * Sets activations_remote_sensor_damper
     * @param int $activations_remote_sensor_damper activations_remote_sensor_damper integer
     * @return $this
     */
    public function setActivationsRemoteSensorDamper($activations_remote_sensor_damper)
    {
        $this->container['activations_remote_sensor_damper'] = $activations_remote_sensor_damper;

        return $this;
    }

    /**
     * Gets activations_remote_shield_booster
     * @return int
     */
    public function getActivationsRemoteShieldBooster()
    {
        return $this->container['activations_remote_shield_booster'];
    }

    /**
     * Sets activations_remote_shield_booster
     * @param int $activations_remote_shield_booster activations_remote_shield_booster integer
     * @return $this
     */
    public function setActivationsRemoteShieldBooster($activations_remote_shield_booster)
    {
        $this->container['activations_remote_shield_booster'] = $activations_remote_shield_booster;

        return $this;
    }

    /**
     * Gets activations_remote_tracking_computer
     * @return int
     */
    public function getActivationsRemoteTrackingComputer()
    {
        return $this->container['activations_remote_tracking_computer'];
    }

    /**
     * Sets activations_remote_tracking_computer
     * @param int $activations_remote_tracking_computer activations_remote_tracking_computer integer
     * @return $this
     */
    public function setActivationsRemoteTrackingComputer($activations_remote_tracking_computer)
    {
        $this->container['activations_remote_tracking_computer'] = $activations_remote_tracking_computer;

        return $this;
    }

    /**
     * Gets activations_salvager
     * @return int
     */
    public function getActivationsSalvager()
    {
        return $this->container['activations_salvager'];
    }

    /**
     * Sets activations_salvager
     * @param int $activations_salvager activations_salvager integer
     * @return $this
     */
    public function setActivationsSalvager($activations_salvager)
    {
        $this->container['activations_salvager'] = $activations_salvager;

        return $this;
    }

    /**
     * Gets activations_sensor_booster
     * @return int
     */
    public function getActivationsSensorBooster()
    {
        return $this->container['activations_sensor_booster'];
    }

    /**
     * Sets activations_sensor_booster
     * @param int $activations_sensor_booster activations_sensor_booster integer
     * @return $this
     */
    public function setActivationsSensorBooster($activations_sensor_booster)
    {
        $this->container['activations_sensor_booster'] = $activations_sensor_booster;

        return $this;
    }

    /**
     * Gets activations_shield_booster
     * @return int
     */
    public function getActivationsShieldBooster()
    {
        return $this->container['activations_shield_booster'];
    }

    /**
     * Sets activations_shield_booster
     * @param int $activations_shield_booster activations_shield_booster integer
     * @return $this
     */
    public function setActivationsShieldBooster($activations_shield_booster)
    {
        $this->container['activations_shield_booster'] = $activations_shield_booster;

        return $this;
    }

    /**
     * Gets activations_shield_hardener
     * @return int
     */
    public function getActivationsShieldHardener()
    {
        return $this->container['activations_shield_hardener'];
    }

    /**
     * Sets activations_shield_hardener
     * @param int $activations_shield_hardener activations_shield_hardener integer
     * @return $this
     */
    public function setActivationsShieldHardener($activations_shield_hardener)
    {
        $this->container['activations_shield_hardener'] = $activations_shield_hardener;

        return $this;
    }

    /**
     * Gets activations_ship_scanner
     * @return int
     */
    public function getActivationsShipScanner()
    {
        return $this->container['activations_ship_scanner'];
    }

    /**
     * Sets activations_ship_scanner
     * @param int $activations_ship_scanner activations_ship_scanner integer
     * @return $this
     */
    public function setActivationsShipScanner($activations_ship_scanner)
    {
        $this->container['activations_ship_scanner'] = $activations_ship_scanner;

        return $this;
    }

    /**
     * Gets activations_siege
     * @return int
     */
    public function getActivationsSiege()
    {
        return $this->container['activations_siege'];
    }

    /**
     * Sets activations_siege
     * @param int $activations_siege activations_siege integer
     * @return $this
     */
    public function setActivationsSiege($activations_siege)
    {
        $this->container['activations_siege'] = $activations_siege;

        return $this;
    }

    /**
     * Gets activations_smart_bomb
     * @return int
     */
    public function getActivationsSmartBomb()
    {
        return $this->container['activations_smart_bomb'];
    }

    /**
     * Sets activations_smart_bomb
     * @param int $activations_smart_bomb activations_smart_bomb integer
     * @return $this
     */
    public function setActivationsSmartBomb($activations_smart_bomb)
    {
        $this->container['activations_smart_bomb'] = $activations_smart_bomb;

        return $this;
    }

    /**
     * Gets activations_stasis_web
     * @return int
     */
    public function getActivationsStasisWeb()
    {
        return $this->container['activations_stasis_web'];
    }

    /**
     * Sets activations_stasis_web
     * @param int $activations_stasis_web activations_stasis_web integer
     * @return $this
     */
    public function setActivationsStasisWeb($activations_stasis_web)
    {
        $this->container['activations_stasis_web'] = $activations_stasis_web;

        return $this;
    }

    /**
     * Gets activations_strip_miner
     * @return int
     */
    public function getActivationsStripMiner()
    {
        return $this->container['activations_strip_miner'];
    }

    /**
     * Sets activations_strip_miner
     * @param int $activations_strip_miner activations_strip_miner integer
     * @return $this
     */
    public function setActivationsStripMiner($activations_strip_miner)
    {
        $this->container['activations_strip_miner'] = $activations_strip_miner;

        return $this;
    }

    /**
     * Gets activations_super_weapon
     * @return int
     */
    public function getActivationsSuperWeapon()
    {
        return $this->container['activations_super_weapon'];
    }

    /**
     * Sets activations_super_weapon
     * @param int $activations_super_weapon activations_super_weapon integer
     * @return $this
     */
    public function setActivationsSuperWeapon($activations_super_weapon)
    {
        $this->container['activations_super_weapon'] = $activations_super_weapon;

        return $this;
    }

    /**
     * Gets activations_survey_scanner
     * @return int
     */
    public function getActivationsSurveyScanner()
    {
        return $this->container['activations_survey_scanner'];
    }

    /**
     * Sets activations_survey_scanner
     * @param int $activations_survey_scanner activations_survey_scanner integer
     * @return $this
     */
    public function setActivationsSurveyScanner($activations_survey_scanner)
    {
        $this->container['activations_survey_scanner'] = $activations_survey_scanner;

        return $this;
    }

    /**
     * Gets activations_target_breaker
     * @return int
     */
    public function getActivationsTargetBreaker()
    {
        return $this->container['activations_target_breaker'];
    }

    /**
     * Sets activations_target_breaker
     * @param int $activations_target_breaker activations_target_breaker integer
     * @return $this
     */
    public function setActivationsTargetBreaker($activations_target_breaker)
    {
        $this->container['activations_target_breaker'] = $activations_target_breaker;

        return $this;
    }

    /**
     * Gets activations_target_painter
     * @return int
     */
    public function getActivationsTargetPainter()
    {
        return $this->container['activations_target_painter'];
    }

    /**
     * Sets activations_target_painter
     * @param int $activations_target_painter activations_target_painter integer
     * @return $this
     */
    public function setActivationsTargetPainter($activations_target_painter)
    {
        $this->container['activations_target_painter'] = $activations_target_painter;

        return $this;
    }

    /**
     * Gets activations_tracking_computer
     * @return int
     */
    public function getActivationsTrackingComputer()
    {
        return $this->container['activations_tracking_computer'];
    }

    /**
     * Sets activations_tracking_computer
     * @param int $activations_tracking_computer activations_tracking_computer integer
     * @return $this
     */
    public function setActivationsTrackingComputer($activations_tracking_computer)
    {
        $this->container['activations_tracking_computer'] = $activations_tracking_computer;

        return $this;
    }

    /**
     * Gets activations_tracking_disruptor
     * @return int
     */
    public function getActivationsTrackingDisruptor()
    {
        return $this->container['activations_tracking_disruptor'];
    }

    /**
     * Sets activations_tracking_disruptor
     * @param int $activations_tracking_disruptor activations_tracking_disruptor integer
     * @return $this
     */
    public function setActivationsTrackingDisruptor($activations_tracking_disruptor)
    {
        $this->container['activations_tracking_disruptor'] = $activations_tracking_disruptor;

        return $this;
    }

    /**
     * Gets activations_tractor_beam
     * @return int
     */
    public function getActivationsTractorBeam()
    {
        return $this->container['activations_tractor_beam'];
    }

    /**
     * Sets activations_tractor_beam
     * @param int $activations_tractor_beam activations_tractor_beam integer
     * @return $this
     */
    public function setActivationsTractorBeam($activations_tractor_beam)
    {
        $this->container['activations_tractor_beam'] = $activations_tractor_beam;

        return $this;
    }

    /**
     * Gets activations_triage
     * @return int
     */
    public function getActivationsTriage()
    {
        return $this->container['activations_triage'];
    }

    /**
     * Sets activations_triage
     * @param int $activations_triage activations_triage integer
     * @return $this
     */
    public function setActivationsTriage($activations_triage)
    {
        $this->container['activations_triage'] = $activations_triage;

        return $this;
    }

    /**
     * Gets activations_warp_disrupt_field_generator
     * @return int
     */
    public function getActivationsWarpDisruptFieldGenerator()
    {
        return $this->container['activations_warp_disrupt_field_generator'];
    }

    /**
     * Sets activations_warp_disrupt_field_generator
     * @param int $activations_warp_disrupt_field_generator activations_warp_disrupt_field_generator integer
     * @return $this
     */
    public function setActivationsWarpDisruptFieldGenerator($activations_warp_disrupt_field_generator)
    {
        $this->container['activations_warp_disrupt_field_generator'] = $activations_warp_disrupt_field_generator;

        return $this;
    }

    /**
     * Gets activations_warp_scrambler
     * @return int
     */
    public function getActivationsWarpScrambler()
    {
        return $this->container['activations_warp_scrambler'];
    }

    /**
     * Sets activations_warp_scrambler
     * @param int $activations_warp_scrambler activations_warp_scrambler integer
     * @return $this
     */
    public function setActivationsWarpScrambler($activations_warp_scrambler)
    {
        $this->container['activations_warp_scrambler'] = $activations_warp_scrambler;

        return $this;
    }

    /**
     * Gets link_weapons
     * @return int
     */
    public function getLinkWeapons()
    {
        return $this->container['link_weapons'];
    }

    /**
     * Sets link_weapons
     * @param int $link_weapons link_weapons integer
     * @return $this
     */
    public function setLinkWeapons($link_weapons)
    {
        $this->container['link_weapons'] = $link_weapons;

        return $this;
    }

    /**
     * Gets overload
     * @return int
     */
    public function getOverload()
    {
        return $this->container['overload'];
    }

    /**
     * Sets overload
     * @param int $overload overload integer
     * @return $this
     */
    public function setOverload($overload)
    {
        $this->container['overload'] = $overload;

        return $this;
    }

    /**
     * Gets repairs
     * @return int
     */
    public function getRepairs()
    {
        return $this->container['repairs'];
    }

    /**
     * Sets repairs
     * @param int $repairs repairs integer
     * @return $this
     */
    public function setRepairs($repairs)
    {
        $this->container['repairs'] = $repairs;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


