<?php
/**
 * GetCharactersCharacterIdContracts200OkTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * GetCharactersCharacterIdContracts200OkTest Class Doc Comment
 *
 * @category    Class */
// * @description 200 ok object
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GetCharactersCharacterIdContracts200OkTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "GetCharactersCharacterIdContracts200Ok"
     */
    public function testGetCharactersCharacterIdContracts200Ok()
    {

    }

    /**
     * Test attribute "acceptor_id"
     */
    public function testPropertyAcceptorId()
    {

    }

    /**
     * Test attribute "assignee_id"
     */
    public function testPropertyAssigneeId()
    {

    }

    /**
     * Test attribute "availability"
     */
    public function testPropertyAvailability()
    {

    }

    /**
     * Test attribute "buyout"
     */
    public function testPropertyBuyout()
    {

    }

    /**
     * Test attribute "collateral"
     */
    public function testPropertyCollateral()
    {

    }

    /**
     * Test attribute "contract_id"
     */
    public function testPropertyContractId()
    {

    }

    /**
     * Test attribute "date_accepted"
     */
    public function testPropertyDateAccepted()
    {

    }

    /**
     * Test attribute "date_completed"
     */
    public function testPropertyDateCompleted()
    {

    }

    /**
     * Test attribute "date_expired"
     */
    public function testPropertyDateExpired()
    {

    }

    /**
     * Test attribute "date_issued"
     */
    public function testPropertyDateIssued()
    {

    }

    /**
     * Test attribute "days_to_complete"
     */
    public function testPropertyDaysToComplete()
    {

    }

    /**
     * Test attribute "end_location_id"
     */
    public function testPropertyEndLocationId()
    {

    }

    /**
     * Test attribute "for_corporation"
     */
    public function testPropertyForCorporation()
    {

    }

    /**
     * Test attribute "issuer_corporation_id"
     */
    public function testPropertyIssuerCorporationId()
    {

    }

    /**
     * Test attribute "issuer_id"
     */
    public function testPropertyIssuerId()
    {

    }

    /**
     * Test attribute "price"
     */
    public function testPropertyPrice()
    {

    }

    /**
     * Test attribute "reward"
     */
    public function testPropertyReward()
    {

    }

    /**
     * Test attribute "start_location_id"
     */
    public function testPropertyStartLocationId()
    {

    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {

    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {

    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {

    }

    /**
     * Test attribute "volume"
     */
    public function testPropertyVolume()
    {

    }

}
