<?php
/**
 * GetMarketsRegionIdOrders200OkTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * GetMarketsRegionIdOrders200OkTest Class Doc Comment
 *
 * @category    Class */
// * @description 200 ok object
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GetMarketsRegionIdOrders200OkTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "GetMarketsRegionIdOrders200Ok"
     */
    public function testGetMarketsRegionIdOrders200Ok()
    {

    }

    /**
     * Test attribute "duration"
     */
    public function testPropertyDuration()
    {

    }

    /**
     * Test attribute "is_buy_order"
     */
    public function testPropertyIsBuyOrder()
    {

    }

    /**
     * Test attribute "issued"
     */
    public function testPropertyIssued()
    {

    }

    /**
     * Test attribute "location_id"
     */
    public function testPropertyLocationId()
    {

    }

    /**
     * Test attribute "min_volume"
     */
    public function testPropertyMinVolume()
    {

    }

    /**
     * Test attribute "order_id"
     */
    public function testPropertyOrderId()
    {

    }

    /**
     * Test attribute "price"
     */
    public function testPropertyPrice()
    {

    }

    /**
     * Test attribute "range"
     */
    public function testPropertyRange()
    {

    }

    /**
     * Test attribute "type_id"
     */
    public function testPropertyTypeId()
    {

    }

    /**
     * Test attribute "volume_remain"
     */
    public function testPropertyVolumeRemain()
    {

    }

    /**
     * Test attribute "volume_total"
     */
    public function testPropertyVolumeTotal()
    {

    }

}
