<?php
/**
 * V2characterscharacterIdstatsTravelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.8.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * V2characterscharacterIdstatsTravelTest Class Doc Comment
 *
 * @category    Class */
// * @description travel object
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class V2characterscharacterIdstatsTravelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "V2characterscharacterIdstatsTravel"
     */
    public function testV2characterscharacterIdstatsTravel()
    {

    }

    /**
     * Test attribute "acceleration_gate_activations"
     */
    public function testPropertyAccelerationGateActivations()
    {

    }

    /**
     * Test attribute "align_to"
     */
    public function testPropertyAlignTo()
    {

    }

    /**
     * Test attribute "distance_warped_high_sec"
     */
    public function testPropertyDistanceWarpedHighSec()
    {

    }

    /**
     * Test attribute "distance_warped_low_sec"
     */
    public function testPropertyDistanceWarpedLowSec()
    {

    }

    /**
     * Test attribute "distance_warped_null_sec"
     */
    public function testPropertyDistanceWarpedNullSec()
    {

    }

    /**
     * Test attribute "distance_warped_wormhole"
     */
    public function testPropertyDistanceWarpedWormhole()
    {

    }

    /**
     * Test attribute "docks_high_sec"
     */
    public function testPropertyDocksHighSec()
    {

    }

    /**
     * Test attribute "docks_low_sec"
     */
    public function testPropertyDocksLowSec()
    {

    }

    /**
     * Test attribute "docks_null_sec"
     */
    public function testPropertyDocksNullSec()
    {

    }

    /**
     * Test attribute "jumps_stargate_high_sec"
     */
    public function testPropertyJumpsStargateHighSec()
    {

    }

    /**
     * Test attribute "jumps_stargate_low_sec"
     */
    public function testPropertyJumpsStargateLowSec()
    {

    }

    /**
     * Test attribute "jumps_stargate_null_sec"
     */
    public function testPropertyJumpsStargateNullSec()
    {

    }

    /**
     * Test attribute "jumps_wormhole"
     */
    public function testPropertyJumpsWormhole()
    {

    }

    /**
     * Test attribute "warps_high_sec"
     */
    public function testPropertyWarpsHighSec()
    {

    }

    /**
     * Test attribute "warps_low_sec"
     */
    public function testPropertyWarpsLowSec()
    {

    }

    /**
     * Test attribute "warps_null_sec"
     */
    public function testPropertyWarpsNullSec()
    {

    }

    /**
     * Test attribute "warps_to_bookmark"
     */
    public function testPropertyWarpsToBookmark()
    {

    }

    /**
     * Test attribute "warps_to_celestial"
     */
    public function testPropertyWarpsToCelestial()
    {

    }

    /**
     * Test attribute "warps_to_fleet_member"
     */
    public function testPropertyWarpsToFleetMember()
    {

    }

    /**
     * Test attribute "warps_to_scan_result"
     */
    public function testPropertyWarpsToScanResult()
    {

    }

    /**
     * Test attribute "warps_wormhole"
     */
    public function testPropertyWarpsWormhole()
    {

    }

}
