<?php
/**
 * V2characterscharacterIdstatsCombatTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.8.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * V2characterscharacterIdstatsCombatTest Class Doc Comment
 *
 * @category    Class */
// * @description combat object
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class V2characterscharacterIdstatsCombatTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "V2characterscharacterIdstatsCombat"
     */
    public function testV2characterscharacterIdstatsCombat()
    {

    }

    /**
     * Test attribute "cap_drainedby_npc"
     */
    public function testPropertyCapDrainedbyNpc()
    {

    }

    /**
     * Test attribute "cap_drainedby_pc"
     */
    public function testPropertyCapDrainedbyPc()
    {

    }

    /**
     * Test attribute "cap_draining_pc"
     */
    public function testPropertyCapDrainingPc()
    {

    }

    /**
     * Test attribute "criminal_flag_set"
     */
    public function testPropertyCriminalFlagSet()
    {

    }

    /**
     * Test attribute "damage_from_np_cs_amount"
     */
    public function testPropertyDamageFromNpCsAmount()
    {

    }

    /**
     * Test attribute "damage_from_np_cs_num_shots"
     */
    public function testPropertyDamageFromNpCsNumShots()
    {

    }

    /**
     * Test attribute "damage_from_players_bomb_amount"
     */
    public function testPropertyDamageFromPlayersBombAmount()
    {

    }

    /**
     * Test attribute "damage_from_players_bomb_num_shots"
     */
    public function testPropertyDamageFromPlayersBombNumShots()
    {

    }

    /**
     * Test attribute "damage_from_players_combat_drone_amount"
     */
    public function testPropertyDamageFromPlayersCombatDroneAmount()
    {

    }

    /**
     * Test attribute "damage_from_players_combat_drone_num_shots"
     */
    public function testPropertyDamageFromPlayersCombatDroneNumShots()
    {

    }

    /**
     * Test attribute "damage_from_players_energy_amount"
     */
    public function testPropertyDamageFromPlayersEnergyAmount()
    {

    }

    /**
     * Test attribute "damage_from_players_energy_num_shots"
     */
    public function testPropertyDamageFromPlayersEnergyNumShots()
    {

    }

    /**
     * Test attribute "damage_from_players_fighter_bomber_amount"
     */
    public function testPropertyDamageFromPlayersFighterBomberAmount()
    {

    }

    /**
     * Test attribute "damage_from_players_fighter_bomber_num_shots"
     */
    public function testPropertyDamageFromPlayersFighterBomberNumShots()
    {

    }

    /**
     * Test attribute "damage_from_players_fighter_drone_amount"
     */
    public function testPropertyDamageFromPlayersFighterDroneAmount()
    {

    }

    /**
     * Test attribute "damage_from_players_fighter_drone_num_shots"
     */
    public function testPropertyDamageFromPlayersFighterDroneNumShots()
    {

    }

    /**
     * Test attribute "damage_from_players_hybrid_amount"
     */
    public function testPropertyDamageFromPlayersHybridAmount()
    {

    }

    /**
     * Test attribute "damage_from_players_hybrid_num_shots"
     */
    public function testPropertyDamageFromPlayersHybridNumShots()
    {

    }

    /**
     * Test attribute "damage_from_players_missile_amount"
     */
    public function testPropertyDamageFromPlayersMissileAmount()
    {

    }

    /**
     * Test attribute "damage_from_players_missile_num_shots"
     */
    public function testPropertyDamageFromPlayersMissileNumShots()
    {

    }

    /**
     * Test attribute "damage_from_players_projectile_amount"
     */
    public function testPropertyDamageFromPlayersProjectileAmount()
    {

    }

    /**
     * Test attribute "damage_from_players_projectile_num_shots"
     */
    public function testPropertyDamageFromPlayersProjectileNumShots()
    {

    }

    /**
     * Test attribute "damage_from_players_smart_bomb_amount"
     */
    public function testPropertyDamageFromPlayersSmartBombAmount()
    {

    }

    /**
     * Test attribute "damage_from_players_smart_bomb_num_shots"
     */
    public function testPropertyDamageFromPlayersSmartBombNumShots()
    {

    }

    /**
     * Test attribute "damage_from_players_super_amount"
     */
    public function testPropertyDamageFromPlayersSuperAmount()
    {

    }

    /**
     * Test attribute "damage_from_players_super_num_shots"
     */
    public function testPropertyDamageFromPlayersSuperNumShots()
    {

    }

    /**
     * Test attribute "damage_from_structures_total_amount"
     */
    public function testPropertyDamageFromStructuresTotalAmount()
    {

    }

    /**
     * Test attribute "damage_from_structures_total_num_shots"
     */
    public function testPropertyDamageFromStructuresTotalNumShots()
    {

    }

    /**
     * Test attribute "damage_to_players_bomb_amount"
     */
    public function testPropertyDamageToPlayersBombAmount()
    {

    }

    /**
     * Test attribute "damage_to_players_bomb_num_shots"
     */
    public function testPropertyDamageToPlayersBombNumShots()
    {

    }

    /**
     * Test attribute "damage_to_players_combat_drone_amount"
     */
    public function testPropertyDamageToPlayersCombatDroneAmount()
    {

    }

    /**
     * Test attribute "damage_to_players_combat_drone_num_shots"
     */
    public function testPropertyDamageToPlayersCombatDroneNumShots()
    {

    }

    /**
     * Test attribute "damage_to_players_energy_amount"
     */
    public function testPropertyDamageToPlayersEnergyAmount()
    {

    }

    /**
     * Test attribute "damage_to_players_energy_num_shots"
     */
    public function testPropertyDamageToPlayersEnergyNumShots()
    {

    }

    /**
     * Test attribute "damage_to_players_fighter_bomber_amount"
     */
    public function testPropertyDamageToPlayersFighterBomberAmount()
    {

    }

    /**
     * Test attribute "damage_to_players_fighter_bomber_num_shots"
     */
    public function testPropertyDamageToPlayersFighterBomberNumShots()
    {

    }

    /**
     * Test attribute "damage_to_players_fighter_drone_amount"
     */
    public function testPropertyDamageToPlayersFighterDroneAmount()
    {

    }

    /**
     * Test attribute "damage_to_players_fighter_drone_num_shots"
     */
    public function testPropertyDamageToPlayersFighterDroneNumShots()
    {

    }

    /**
     * Test attribute "damage_to_players_hybrid_amount"
     */
    public function testPropertyDamageToPlayersHybridAmount()
    {

    }

    /**
     * Test attribute "damage_to_players_hybrid_num_shots"
     */
    public function testPropertyDamageToPlayersHybridNumShots()
    {

    }

    /**
     * Test attribute "damage_to_players_missile_amount"
     */
    public function testPropertyDamageToPlayersMissileAmount()
    {

    }

    /**
     * Test attribute "damage_to_players_missile_num_shots"
     */
    public function testPropertyDamageToPlayersMissileNumShots()
    {

    }

    /**
     * Test attribute "damage_to_players_projectile_amount"
     */
    public function testPropertyDamageToPlayersProjectileAmount()
    {

    }

    /**
     * Test attribute "damage_to_players_projectile_num_shots"
     */
    public function testPropertyDamageToPlayersProjectileNumShots()
    {

    }

    /**
     * Test attribute "damage_to_players_smart_bomb_amount"
     */
    public function testPropertyDamageToPlayersSmartBombAmount()
    {

    }

    /**
     * Test attribute "damage_to_players_smart_bomb_num_shots"
     */
    public function testPropertyDamageToPlayersSmartBombNumShots()
    {

    }

    /**
     * Test attribute "damage_to_players_super_amount"
     */
    public function testPropertyDamageToPlayersSuperAmount()
    {

    }

    /**
     * Test attribute "damage_to_players_super_num_shots"
     */
    public function testPropertyDamageToPlayersSuperNumShots()
    {

    }

    /**
     * Test attribute "damage_to_structures_total_amount"
     */
    public function testPropertyDamageToStructuresTotalAmount()
    {

    }

    /**
     * Test attribute "damage_to_structures_total_num_shots"
     */
    public function testPropertyDamageToStructuresTotalNumShots()
    {

    }

    /**
     * Test attribute "deaths_high_sec"
     */
    public function testPropertyDeathsHighSec()
    {

    }

    /**
     * Test attribute "deaths_low_sec"
     */
    public function testPropertyDeathsLowSec()
    {

    }

    /**
     * Test attribute "deaths_null_sec"
     */
    public function testPropertyDeathsNullSec()
    {

    }

    /**
     * Test attribute "deaths_pod_high_sec"
     */
    public function testPropertyDeathsPodHighSec()
    {

    }

    /**
     * Test attribute "deaths_pod_low_sec"
     */
    public function testPropertyDeathsPodLowSec()
    {

    }

    /**
     * Test attribute "deaths_pod_null_sec"
     */
    public function testPropertyDeathsPodNullSec()
    {

    }

    /**
     * Test attribute "deaths_pod_wormhole"
     */
    public function testPropertyDeathsPodWormhole()
    {

    }

    /**
     * Test attribute "deaths_wormhole"
     */
    public function testPropertyDeathsWormhole()
    {

    }

    /**
     * Test attribute "drone_engage"
     */
    public function testPropertyDroneEngage()
    {

    }

    /**
     * Test attribute "dscans"
     */
    public function testPropertyDscans()
    {

    }

    /**
     * Test attribute "duel_requested"
     */
    public function testPropertyDuelRequested()
    {

    }

    /**
     * Test attribute "engagement_register"
     */
    public function testPropertyEngagementRegister()
    {

    }

    /**
     * Test attribute "kills_assists"
     */
    public function testPropertyKillsAssists()
    {

    }

    /**
     * Test attribute "kills_high_sec"
     */
    public function testPropertyKillsHighSec()
    {

    }

    /**
     * Test attribute "kills_low_sec"
     */
    public function testPropertyKillsLowSec()
    {

    }

    /**
     * Test attribute "kills_null_sec"
     */
    public function testPropertyKillsNullSec()
    {

    }

    /**
     * Test attribute "kills_pod_high_sec"
     */
    public function testPropertyKillsPodHighSec()
    {

    }

    /**
     * Test attribute "kills_pod_low_sec"
     */
    public function testPropertyKillsPodLowSec()
    {

    }

    /**
     * Test attribute "kills_pod_null_sec"
     */
    public function testPropertyKillsPodNullSec()
    {

    }

    /**
     * Test attribute "kills_pod_wormhole"
     */
    public function testPropertyKillsPodWormhole()
    {

    }

    /**
     * Test attribute "kills_wormhole"
     */
    public function testPropertyKillsWormhole()
    {

    }

    /**
     * Test attribute "npc_flag_set"
     */
    public function testPropertyNpcFlagSet()
    {

    }

    /**
     * Test attribute "probe_scans"
     */
    public function testPropertyProbeScans()
    {

    }

    /**
     * Test attribute "pvp_flag_set"
     */
    public function testPropertyPvpFlagSet()
    {

    }

    /**
     * Test attribute "repair_armor_by_remote_amount"
     */
    public function testPropertyRepairArmorByRemoteAmount()
    {

    }

    /**
     * Test attribute "repair_armor_remote_amount"
     */
    public function testPropertyRepairArmorRemoteAmount()
    {

    }

    /**
     * Test attribute "repair_armor_self_amount"
     */
    public function testPropertyRepairArmorSelfAmount()
    {

    }

    /**
     * Test attribute "repair_capacitor_by_remote_amount"
     */
    public function testPropertyRepairCapacitorByRemoteAmount()
    {

    }

    /**
     * Test attribute "repair_capacitor_remote_amount"
     */
    public function testPropertyRepairCapacitorRemoteAmount()
    {

    }

    /**
     * Test attribute "repair_capacitor_self_amount"
     */
    public function testPropertyRepairCapacitorSelfAmount()
    {

    }

    /**
     * Test attribute "repair_hull_by_remote_amount"
     */
    public function testPropertyRepairHullByRemoteAmount()
    {

    }

    /**
     * Test attribute "repair_hull_remote_amount"
     */
    public function testPropertyRepairHullRemoteAmount()
    {

    }

    /**
     * Test attribute "repair_hull_self_amount"
     */
    public function testPropertyRepairHullSelfAmount()
    {

    }

    /**
     * Test attribute "repair_shield_by_remote_amount"
     */
    public function testPropertyRepairShieldByRemoteAmount()
    {

    }

    /**
     * Test attribute "repair_shield_remote_amount"
     */
    public function testPropertyRepairShieldRemoteAmount()
    {

    }

    /**
     * Test attribute "repair_shield_self_amount"
     */
    public function testPropertyRepairShieldSelfAmount()
    {

    }

    /**
     * Test attribute "self_destructs"
     */
    public function testPropertySelfDestructs()
    {

    }

    /**
     * Test attribute "warp_scramble_pc"
     */
    public function testPropertyWarpScramblePc()
    {

    }

    /**
     * Test attribute "warp_scrambledby_npc"
     */
    public function testPropertyWarpScrambledbyNpc()
    {

    }

    /**
     * Test attribute "warp_scrambledby_pc"
     */
    public function testPropertyWarpScrambledbyPc()
    {

    }

    /**
     * Test attribute "weapon_flag_set"
     */
    public function testPropertyWeaponFlagSet()
    {

    }

    /**
     * Test attribute "webifiedby_npc"
     */
    public function testPropertyWebifiedbyNpc()
    {

    }

    /**
     * Test attribute "webifiedby_pc"
     */
    public function testPropertyWebifiedbyPc()
    {

    }

    /**
     * Test attribute "webifying_pc"
     */
    public function testPropertyWebifyingPc()
    {

    }

}
