<?php
/**
 * V2characterscharacterIdstatsMarketTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.8.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * V2characterscharacterIdstatsMarketTest Class Doc Comment
 *
 * @category    Class */
// * @description market object
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class V2characterscharacterIdstatsMarketTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "V2characterscharacterIdstatsMarket"
     */
    public function testV2characterscharacterIdstatsMarket()
    {

    }

    /**
     * Test attribute "accept_contracts_courier"
     */
    public function testPropertyAcceptContractsCourier()
    {

    }

    /**
     * Test attribute "accept_contracts_item_exchange"
     */
    public function testPropertyAcceptContractsItemExchange()
    {

    }

    /**
     * Test attribute "buy_orders_placed"
     */
    public function testPropertyBuyOrdersPlaced()
    {

    }

    /**
     * Test attribute "cancel_market_order"
     */
    public function testPropertyCancelMarketOrder()
    {

    }

    /**
     * Test attribute "create_contracts_auction"
     */
    public function testPropertyCreateContractsAuction()
    {

    }

    /**
     * Test attribute "create_contracts_courier"
     */
    public function testPropertyCreateContractsCourier()
    {

    }

    /**
     * Test attribute "create_contracts_item_exchange"
     */
    public function testPropertyCreateContractsItemExchange()
    {

    }

    /**
     * Test attribute "deliver_courier_contract"
     */
    public function testPropertyDeliverCourierContract()
    {

    }

    /**
     * Test attribute "isk_gained"
     */
    public function testPropertyIskGained()
    {

    }

    /**
     * Test attribute "isk_spent"
     */
    public function testPropertyIskSpent()
    {

    }

    /**
     * Test attribute "modify_market_order"
     */
    public function testPropertyModifyMarketOrder()
    {

    }

    /**
     * Test attribute "search_contracts"
     */
    public function testPropertySearchContracts()
    {

    }

    /**
     * Test attribute "sell_orders_placed"
     */
    public function testPropertySellOrdersPlaced()
    {

    }

}
