<?php
/**
 * V2characterscharacterIdstatsSocialTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.8.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * V2characterscharacterIdstatsSocialTest Class Doc Comment
 *
 * @category    Class */
// * @description social object
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class V2characterscharacterIdstatsSocialTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "V2characterscharacterIdstatsSocial"
     */
    public function testV2characterscharacterIdstatsSocial()
    {

    }

    /**
     * Test attribute "add_contact_bad"
     */
    public function testPropertyAddContactBad()
    {

    }

    /**
     * Test attribute "add_contact_good"
     */
    public function testPropertyAddContactGood()
    {

    }

    /**
     * Test attribute "add_contact_high"
     */
    public function testPropertyAddContactHigh()
    {

    }

    /**
     * Test attribute "add_contact_horrible"
     */
    public function testPropertyAddContactHorrible()
    {

    }

    /**
     * Test attribute "add_contact_neutral"
     */
    public function testPropertyAddContactNeutral()
    {

    }

    /**
     * Test attribute "add_note"
     */
    public function testPropertyAddNote()
    {

    }

    /**
     * Test attribute "added_as_contact_bad"
     */
    public function testPropertyAddedAsContactBad()
    {

    }

    /**
     * Test attribute "added_as_contact_good"
     */
    public function testPropertyAddedAsContactGood()
    {

    }

    /**
     * Test attribute "added_as_contact_high"
     */
    public function testPropertyAddedAsContactHigh()
    {

    }

    /**
     * Test attribute "added_as_contact_horrible"
     */
    public function testPropertyAddedAsContactHorrible()
    {

    }

    /**
     * Test attribute "added_as_contact_neutral"
     */
    public function testPropertyAddedAsContactNeutral()
    {

    }

    /**
     * Test attribute "calendar_event_created"
     */
    public function testPropertyCalendarEventCreated()
    {

    }

    /**
     * Test attribute "chat_messages_alliance"
     */
    public function testPropertyChatMessagesAlliance()
    {

    }

    /**
     * Test attribute "chat_messages_constellation"
     */
    public function testPropertyChatMessagesConstellation()
    {

    }

    /**
     * Test attribute "chat_messages_corporation"
     */
    public function testPropertyChatMessagesCorporation()
    {

    }

    /**
     * Test attribute "chat_messages_fleet"
     */
    public function testPropertyChatMessagesFleet()
    {

    }

    /**
     * Test attribute "chat_messages_region"
     */
    public function testPropertyChatMessagesRegion()
    {

    }

    /**
     * Test attribute "chat_messages_solarsystem"
     */
    public function testPropertyChatMessagesSolarsystem()
    {

    }

    /**
     * Test attribute "chat_messages_warfaction"
     */
    public function testPropertyChatMessagesWarfaction()
    {

    }

    /**
     * Test attribute "chat_total_message_length"
     */
    public function testPropertyChatTotalMessageLength()
    {

    }

    /**
     * Test attribute "direct_trades"
     */
    public function testPropertyDirectTrades()
    {

    }

    /**
     * Test attribute "fleet_broadcasts"
     */
    public function testPropertyFleetBroadcasts()
    {

    }

    /**
     * Test attribute "fleet_joins"
     */
    public function testPropertyFleetJoins()
    {

    }

    /**
     * Test attribute "mails_received"
     */
    public function testPropertyMailsReceived()
    {

    }

    /**
     * Test attribute "mails_sent"
     */
    public function testPropertyMailsSent()
    {

    }

}
