<?php
/**
 * CorporationApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.5.6
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * CorporationApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CorporationApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for getCorporationsCorporationId
     *
     * Get corporation information.
     *
     */
    public function testGetCorporationsCorporationId()
    {

    }

    /**
     * Test case for getCorporationsCorporationIdAlliancehistory
     *
     * Get alliance history.
     *
     */
    public function testGetCorporationsCorporationIdAlliancehistory()
    {

    }

    /**
     * Test case for getCorporationsCorporationIdBlueprints
     *
     * Get corporation blueprints.
     *
     */
    public function testGetCorporationsCorporationIdBlueprints()
    {

    }

    /**
     * Test case for getCorporationsCorporationIdDivisions
     *
     * Get corporation divisions.
     *
     */
    public function testGetCorporationsCorporationIdDivisions()
    {

    }

    /**
     * Test case for getCorporationsCorporationIdIcons
     *
     * Get corporation icon.
     *
     */
    public function testGetCorporationsCorporationIdIcons()
    {

    }

    /**
     * Test case for getCorporationsCorporationIdMembers
     *
     * Get corporation members.
     *
     */
    public function testGetCorporationsCorporationIdMembers()
    {

    }

    /**
     * Test case for getCorporationsCorporationIdMembersLimit
     *
     * Get corporation member limit.
     *
     */
    public function testGetCorporationsCorporationIdMembersLimit()
    {

    }

    /**
     * Test case for getCorporationsCorporationIdMembertracking
     *
     * Track corporation members.
     *
     */
    public function testGetCorporationsCorporationIdMembertracking()
    {

    }

    /**
     * Test case for getCorporationsCorporationIdRoles
     *
     * Get corporation member roles.
     *
     */
    public function testGetCorporationsCorporationIdRoles()
    {

    }

    /**
     * Test case for getCorporationsCorporationIdStructures
     *
     * Get corporation structures.
     *
     */
    public function testGetCorporationsCorporationIdStructures()
    {

    }

    /**
     * Test case for getCorporationsCorporationIdTitles
     *
     * Get corporation titles.
     *
     */
    public function testGetCorporationsCorporationIdTitles()
    {

    }

    /**
     * Test case for getCorporationsNames
     *
     * Get corporation names.
     *
     */
    public function testGetCorporationsNames()
    {

    }

    /**
     * Test case for getCorporationsNpccorps
     *
     * Get npc corporations.
     *
     */
    public function testGetCorporationsNpccorps()
    {

    }

    /**
     * Test case for putCorporationsCorporationIdStructuresStructureId
     *
     * Update structure vulnerability schedule.
     *
     */
    public function testPutCorporationsCorporationIdStructuresStructureId()
    {

    }

}
